### ISSUE TITLE
OutOfMemory (or SegFault) error in invoke_tfunc

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#10878]
```
julia> function g(x; kw...)
       end
g (generic function with 1 method)

julia> function invoke_g()
       return invoke(g, Tuple{Any}, 1)
       end
invoke_g (generic function with 1 method)

julia> println(@code_typed invoke_g())
ERROR: OutOfMemoryError()
 in invoke_tfunc at ./inference.jl:721
 in code_typed at ./inference.jl:3253
```

Julia version.
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4331 (2015-04-17 20:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit ed020a5* (0 days old master)
|__/                   |  x86_64-unknown-linux-gnu
```

**Comment by yuyichao** [comment]
and by "similar" I mean occasionally it SegFault

BackTrace below

```
Program received signal SIGSEGV, Segmentation fault.
jl_type_intersection_matching (a=a@entry=0x7f79339f7960, b=0x7f79369d4010, penv=penv@entry=0x7fff211122e0, tvars=tvars@entry=0x7f79369cf890) at jltypes.c:1435
1435                jl_tvar_t *ntv = jl_new_typevar(tv->name, tv->lb, tv->ub);
(gdb) bt
#0  jl_type_intersection_matching (a=a@entry=0x7f79339f7960, b=0x7f79369d4010, penv=penv@entry=0x7fff211122e0, tvars=tvars@entry=0x7f79369cf890) at jltypes.c:1435
#1  0x00007f7b380a6fbd in lookup_match (a=0x7f79339f7960, b=<optimized out>, penv=penv@entry=0x7fff211122e0, tvars=0x7f79369cf890) at gf.c:913
#2  0x00007f7b380ac666 in jl_match_method (type=<optimized out>, sig=<optimized out>, tvars=<optimized out>) at gf.c:1849
#3  0x00007f7b394e6593 in julia_invoke_tfunc_43831 (f=<optimized out>, types=<optimized out>, argtype=<optimized out>) at inference.jl:721
#4  0x00007f7b380abd64 in jl_apply (nargs=3, args=0x7fff21112720, f=<optimized out>) at julia.h:1280
#5  jl_apply_generic (F=0x7f793562cad8, args=0x7fff21112720, nargs=<optimized out>) at gf.c:1679
#6  0x00007f7b355ae350 in julia_abstract_call_26403 (f=<optimized out>, fargs=<optimized out>, argtypes=<optimized out>, vtypes=<optimized out>, sv=<optimized out>, 
    e=<optimized out>) at inference.jl:819
#7  0x00007f7b380abcc8 in jl_apply (nargs=6, args=0x7fff211128d8, f=<optimized out>) at julia.h:1280
#8  jl_apply_generic (F=0x7f79351a1f00, args=0x7fff211128d8, nargs=6) at gf.c:1655
#9  0x00007f7b355b28bd in julia_abstract_eval_call_26461 (e=<optimized out>, vtypes=<optimized out>, sv=<optimized out>) at inference.jl:900
#10 0x00007f7b355b2f23 in julia_abstract_eval_26465 (e=<optimized out>, vtypes=<optimized out>, sv=<optimized out>) at inference.jl:927
#11 0x00007f7b380abcc8 in jl_apply (nargs=3, args=0x7fff21112f08, f=<optimized out>) at julia.h:1280
#12 jl_apply_generic (F=0x7f793546ecc0, args=0x7fff21112f08, nargs=3) at gf.c:1655
#13 0x00007f7b355ba6b9 in julia_typeinf_uncached_26585 (cop=<optimized out>, optimize=<optimized out>) at inference.jl:1587
#14 0x00007f7b355bbe60 in jlcall_typeinf_uncached_26585 () from /usr/lib/julia/sys.so
#15 0x00007f7b380abcc8 in jl_apply (nargs=7, args=0x7fff211130d0, f=<optimized out>) at julia.h:1280
#16 jl_apply_generic (F=0x7f7934e2f8c8, args=0x7fff211130d0, nargs=7) at gf.c:1655
#17 0x00007f7b355bc3e7 in julia_typeinf_26603 (cop=0x100000001, needtree=0x100000001) at inference.jl:1303
#18 0x00007f7b355bcae6 in jlcall_typeinf_26603 () from /usr/lib/julia/sys.so
#19 0x00007f7b380abcc8 in jl_apply (nargs=6, args=0x7fff211132d8, f=<optimized out>) at julia.h:1280
#20 jl_apply_generic (F=0x7f7935492338, args=0x7fff211132d8, nargs=6) at gf.c:1655
#21 0x00007f7b394ea49e in julia___code_typed#9___43829 () at inference.jl:3253
#22 0x00007f7b394ea866 in jlcall___code_typed#9___43829 ()
#23 0x00007f7b380abd64 in jl_apply (nargs=3, args=0x7fff21113410, f=<optimized out>) at julia.h:1280
#24 jl_apply_generic (F=0x7f7934a661d0, args=0x7fff21113410, nargs=<optimized out>) at gf.c:1679
#25 0x00007f7b394ed07c in julia_code_typed_43828 ()
#26 0x00007f7b380abd64 in jl_apply (nargs=2, args=0x7fff211134e8, f=<optimized out>) at julia.h:1280
#27 jl_apply_generic (F=0x7f7935762798, args=0x7fff211134e8, nargs=<optimized out>) at gf.c:1679
#28 0x00007f7b38100593 in jl_apply (nargs=2, args=0x7fff211134e8, f=0x7f7935762798) at julia.h:1280
#29 do_call (f=f@entry=0x7f7935762798, args=args@entry=0x7f7935bf8e28, nargs=nargs@entry=2, eval0=eval0@entry=0x0, locals=locals@entry=0x0, nl=nl@entry=0, ngensym=0)
    at interpreter.c:63
#30 0x00007f7b380ff910 in eval (e=0x7f7935befd28, locals=locals@entry=0x0, nl=nl@entry=0, ngensym=ngensym@entry=0) at interpreter.c:210
#31 0x00007f7b381004bb in jl_interpret_toplevel_expr (e=<optimized out>) at interpreter.c:25
#32 0x00007f7b38113076 in jl_toplevel_eval_flex (e=<optimized out>, fast=fast@entry=1) at toplevel.c:504
#33 0x00007f7b38113bb4 in jl_toplevel_eval_flex (fast=1, e=<optimized out>) at toplevel.c:548
#34 jl_parse_eval_all (fname=fname@entry=0x7f7935ad7ae0 "/home/yuyichao/tmp/julia_invoke_tfunc.jl") at toplevel.c:552
#35 0x00007f7b38113daf in jl_load (fname=0x7f7935ad7ae0 "/home/yuyichao/tmp/julia_invoke_tfunc.jl") at toplevel.c:591
#36 0x00007f7b354f71d0 in julia_include_23412 (fname=<optimized out>) at boot.jl:250
#37 0x00007f7b380abcc8 in jl_apply (nargs=1, args=0x7fff21113d60, f=<optimized out>) at julia.h:1280
#38 jl_apply_generic (F=0x7f7933a18dd0, args=0x7fff21113d60, nargs=1) at gf.c:1655
#39 0x00007f7b39485225 in ?? ()
#40 0x0000000002206980 in ?? ()
#41 0x00007f7b380f41c4 in untrack (MD=@0x7fff21113ca0: 0x7fff21113c18) at /usr/include/llvm/IR/MetadataTracking.h:69
#42 untrack (this=0x7fff21113ca0) at /usr/include/llvm/IR/TrackingMDRef.h:90
#43 ~TrackingMDRef (this=0x7fff21113ca0, __in_chrg=<optimized out>) at /usr/include/llvm/IR/TrackingMDRef.h:56
---Type <return> to continue, or q <return> to quit---
#44 ~TypedTrackingMDRef (this=0x7fff21113ca0, __in_chrg=<optimized out>) at /usr/include/llvm/IR/TrackingMDRef.h:105
#45 ~DebugLoc (this=0x7fff21113ca0, __in_chrg=<optimized out>) at /usr/include/llvm/IR/DebugLoc.h:30
#46 to_function (li=0x87e0e4cd871436ed) at codegen.cpp:674
#47 0x00007f7b380abd64 in jl_apply (nargs=554778432, args=0x7fff21113c30, f=<optimized out>) at julia.h:1280
#48 jl_apply_generic (F=0x7fff21113d60, args=0x7fff21113c30, nargs=<optimized out>) at gf.c:1679
#49 0x00007f7b35762a9e in julia_process_options_41872 (opts=<optimized out>, args=<optimized out>) at client.jl:299
#50 0x00007f7b3576166c in julia__start_41871 () at client.jl:398
#51 0x00007f7b357620a9 in jlcall.start_41871 () from /usr/lib/julia/sys.so
#52 0x00007f7b380abcc8 in jl_apply (nargs=0, args=0x0, f=<optimized out>) at julia.h:1280
#53 jl_apply_generic (F=0x7f79349fc100, args=0x0, nargs=0) at gf.c:1655
#54 0x000000000040186b in jl_apply (nargs=0, args=0x0, f=<optimized out>) at ../src/julia.h:1280
#55 true_main (argc=<optimized out>, argv=<optimized out>) at repl.c:439
#56 0x00000000004013df in main (argc=1, argv=0x7fff21114498) at repl.c:492
```

**Comment by yuyichao** [comment]
OTOH, the old signature of invoke works just fine. So I guess it's the typeinference of invoke not ready for the new signature yet?

```
julia> function g(x; kw...)
       end
g (generic function with 1 method)

julia> function invoke_g1()
       return invoke(g, (Any,), 1)
       end
invoke_g1 (generic function with 1 method)

julia> function invoke_g2()
       return invoke(g, Tuple{Any}, 1)
       end
invoke_g2 (generic function with 1 method)

julia> @code_typed invoke_g1()
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[], Any[Any[],Any[],Any[],Any[]], :(begin  # none, line 2:
        return invoke(g,(top(tuple))(Any)::Tuple{DataType},1)::Any
    end::Any))))

julia> @code_typed invoke_g2()

signal (11): 段错误
unknown function (ip: 1478794615)
unknown function (ip: 1478819773)
jl_match_method at /usr/bin/../lib/julia/libjulia.so (unknown line)
invoke_tfunc at ./inference.jl:721
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 1433760592)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 1433778365)
unknown function (ip: 1433780003)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 1433810617)
unknown function (ip: 1433816672)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 1433818087)
unknown function (ip: 1433819878)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
code_typed at ./inference.jl:3253
unknown function (ip: 1403340902)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 1403351164)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
unknown function (ip: 1479185811)
unknown function (ip: 1479182608)
unknown function (ip: 1479262326)
jl_toplevel_eval_in at /usr/bin/../lib/julia/libjulia.so (unknown line)
eval_user_input at ./REPL.jl:60
unknown function (ip: 1499379095)
jl_apply_generic at /usr/bin/../lib/julia/libjulia.so (unknown line)
anonymous at ./task.jl:82
unknown function (ip: 1479210752)
unknown function (ip: 0)
[1]    27708 segmentation fault (core dumped)  julia -f
```

**Comment by pao** [comment]
cf #10380 cc @JeffBezanson

**Comment by yuyichao** [comment]
THX.
