### ISSUE TITLE
ImportError: No module named juliadoc

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#11086]
When trying to build the latest `master` Julia via Homebrew, I get the following problem:

```
  Running setup.py develop for JuliaDoc
  Running setup.py develop for sphinx-rtd-theme
Successfully installed JuliaDoc sphinx-rtd-theme-0.1.6
touch -c /private/var/folders/hj/9_1ytr5d57l7kgwggb1w104c0000gn/T/julia20150501-41262-maot89/deps/julia-env/bin/sphin
x-build
. /private/var/folders/hj/9_1ytr5d57l7kgwggb1w104c0000gn/T/julia20150501-41262-maot89/deps/julia-env/bin/activate &&
sphinx-build -b html -d _build/doctrees   . _build/html
Making output directory...
Running Sphinx v1.2.3

Exception occurred:
  File "conf.py", line 16, in <module>
    import juliadoc
ImportError: No module named juliadoc
```

Anyone have any ideas?  This is happening on OSX 10.10, with the following incantation:
```
make prefix=/usr/local/Cellar/julia/HEAD \
 USE_BLAS64=0 \
 FC=/usr/local/bin/gfortran \
 LLVM_CONFIG=llvm-config-3.3 \
 USECLANG=1 \
 VERBOSE=1 \
 LIBBLAS=-lopenblas \
 LIBBLASNAME=libopenblas \
 LIBLAPACK=-lopenblas \
 LIBLAPACKNAME=libopenblas \
 USE_SYSTEM_FFTW=1 \
 USE_SYSTEM_GLPK=1 \
 USE_SYSTEM_GMP=1 \
 USE_SYSTEM_LLVM=1 \
 USE_SYSTEM_PCRE=1 \
 USE_SYSTEM_BLAS=1 \
 USE_SYSTEM_LAPACK=1 \
 USE_SYSTEM_SUITESPARSE=1 \
 USE_SYSTEM_ARPACK=1 \
 USE_SYSTEM_MPFR=1 \
 USE_SYSTEM_LIBGIT2=1 \
 install
```

**Comment by staticfloat** [comment]
Pinging @stevengj and @jiahao because you both seem to have had some experience with the docs stuff.

**Comment by jiahao** [comment]
?

So the error comes after the line  "Running Sphinx v1.2.3" ?

**Comment by staticfloat** [comment]
Oh shoot, edited to add in the actual error message.

**Comment by nalimilan** [comment]
@staticfloat Have you ever been able to build the docs via Homebrew before? The docs are built during `make install` since b554ad4b.

I didn't expect that would create so many issues... If that's so painful, we could only build the docs when explicitly required. My main goal was to get them included in the tarballs so that you don't need Sphynx to build Julia from tarballs.

**Comment by staticfloat** [comment]
I think building the docs during `make install` is great; I just want to figure out why it's breaking here.  Because we use `virtualenv` to install things like `sphinx`, we shouldn't have any issues about `sphinx` being installed or not.

**Comment by jiahao** [comment]
Juliadoc is cloned as as a package within the sphinx virtualenv produced in the doc directory. My first question would be whether we have a python environment clash, either with a different system python or by somehow not activating the virtualenv correctly.

**Comment by staticfloat** [comment]
I think that is what's happening.  From within an interactive `brew` shell:

```
$ make -j1
. /private/var/folders/hj/9_1ytr5d57l7kgwggb1w104c0000gn/T/julia20150501-81613-hepwhl/deps/julia-env/bin/activate && pip install sphinx==1.2.3 \
                      && pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): sphinx==1.2.3 in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): Pygments>=1.2 in /usr/local/lib/python2.7/site-packages (from sphinx==1.2.3)
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.7 in /usr/local/lib/python2.7/site-packages (from sphinx==1.2.3)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.3 in /usr/local/lib/python2.7/site-packages (from sphinx==1.2.3)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.3->sphinx==1.2.3)
Obtaining JuliaDoc from git+https://github.com/JuliaLang/JuliaDoc.git@15e0f6f97ecd08f93504b639956047968e3e6a42#egg=JuliaDoc (from -r requirements.txt (line 1))
  Updating /private/var/folders/hj/9_1ytr5d57l7kgwggb1w104c0000gn/T/julia20150501-81613-hepwhl/deps/julia-env/src/juliadoc clone (to 15e0f6f97ecd08f93504b639956047968e3e6a42)
  Could not find a tag or branch '15e0f6f97ecd08f93504b639956047968e3e6a42', assuming commit.
Obtaining sphinx-rtd-theme from git+https://github.com/snide/sphinx_rtd_theme.git@21e875d3a53ce897089ad690d897252f6063349d#egg=sphinx_rtd_theme (from -r requirements.txt (line 2))
  Updating /private/var/folders/hj/9_1ytr5d57l7kgwggb1w104c0000gn/T/julia20150501-81613-hepwhl/deps/julia-env/src/sphinx-rtd-theme clone (to 21e875d3a53ce897089ad690d897252f6063349d)
  Could not find a tag or branch '21e875d3a53ce897089ad690d897252f6063349d', assuming commit.
Requirement already satisfied (use --upgrade to upgrade): sphinx>=1.1 in /usr/local/lib/python2.7/site-packages (from sphinx-rtd-theme->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Pygments>=1.2 in /usr/local/lib/python2.7/site-packages (from sphinx>=1.1->sphinx-rtd-theme->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.7 in /usr/local/lib/python2.7/site-packages (from sphinx>=1.1->sphinx-rtd-theme->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.3 in /usr/local/lib/python2.7/site-packages (from sphinx>=1.1->sphinx-rtd-theme->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.3->sphinx>=1.1->sphinx-rtd-theme->-r requirements.txt (line 2))
Installing collected packages: JuliaDoc, sphinx-rtd-theme
  Running setup.py develop for JuliaDoc
  Running setup.py develop for sphinx-rtd-theme
Successfully installed JuliaDoc-0.0.0 sphinx-rtd-theme-0.1.5
touch -c /private/var/folders/hj/9_1ytr5d57l7kgwggb1w104c0000gn/T/julia20150501-81613-hepwhl/deps/julia-env/bin/sphinx-build
. /private/var/folders/hj/9_1ytr5d57l7kgwggb1w104c0000gn/T/julia20150501-81613-hepwhl/deps/julia-env/bin/activate && sphinx-build -b jlhelp -d _build/doctrees   . _build/jlhelp
Running Sphinx v1.2.3

Exception occurred:
  File "conf.py", line 16, in <module>
    import juliadoc
ImportError: No module named juliadoc
The full traceback has been saved in /var/folders/hj/9_1ytr5d57l7kgwggb1w104c0000gn/T/sphinx-err-2Fmhdl.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [helpdb.jl] Error 1
```

```
$ python
Python 2.7.9 (default, Jan  7 2015, 11:49:12)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import juliadoc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named juliadoc
>>>
$
```

```
$ . /private/var/folders/hj/9_1ytr5d57l7kgwggb1w104c0000gn/T/julia20150501-81613-hepwhl/deps/julia-env/bin/activate && python
Python 2.7.9 (default, Jan  7 2015, 11:49:12)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import juliadoc
>>>
$
```

It looks to me like the problem is that the `virtualenv` we're creating is inheriting site packages, which causes `sphinx` to not get installed to the `virtualenv`, which then causes the `sphinx` above to be invoked from my global python, and `sphinx` has the interpreter path hardcoded within it.

**Comment by pao** [comment]
`--no-site-packages` is the default since virtualenv 1.7 back in 2011. How old is your virtualenv?

**Comment by staticfloat** [comment]
1.11.6

**Comment by tkelman** [comment]
I had some virtualenv/sphinx issues on Cygwin recently, probably different underlying cause though.

There have been newer upstream virtualenv releases, does bumping https://github.com/JuliaLang/julia/blob/62b9817e8b9aad0ed062318adbf4322bb1c36690/deps/Versions.make#L15 help any?

**Comment by staticfloat** [comment]
Figured it out.  I have a script that adds to `$PYTHONPATH` during login, and entering a virtualenv doesn't clear that out; thus, my external environment would constantly leak into my virtualenv.  I'm not certain if this is something we should try to fix; but at least I can recognize the issue from now on.  :)
