### ISSUE TITLE
Errors when exiting REPL

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#11958]
On REPL exit, I started getting

```
jl_uv_writecb() ERROR: bad file descriptor EBADF
```
(repeated 10 times)

on

```
Julia Version 0.4.0-dev+5712
Commit d092dd0 (2015-06-30 18:30 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.3.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by Keno** [comment]
This happens when you close the file descriptor that STDOUT is trying to use. What code are you running?

**Comment by sbromberger** [comment]
@Keno I'm running betweenness_centrality in LightGraphs.jl - it allocates a lot of memory:

```
julia> @time z = betweenness_centrality(g);
    1515 seconds      (3769 M allocations: 272 GB, 16.63% gc time)
```

I then exited using ^D and got those errors.

**Comment by sbromberger** [comment]
I think I've narrowed it down to the deprecation/error with GZip (https://github.com/JuliaLang/GZip.jl/pull/29):

```
julia>    # I typed ^D here
WARNING: gc_disable() is deprecated, use gc_enable(false) instead.jl_uv_writecb() ERROR: bad file descriptor EBADF
```

If I call gc() before ^D, I don't get the EBADF errors on exit.

**Comment by sbromberger** [comment]
Nope, I take it back:

```
julia> @time z = betweenness_centrality(g);
  92.776 seconds      (380 M allocations: 27235 MB, 6.10% gc time)

julia>  # ^D here
jl_uv_writecb() ERROR: bad file descriptor EBADF
```

**Comment by yuyichao** [comment]
@sbromberger Maybe you can add a breakpoint in the error point in `jl_uv_writecb` and see the backtrace when it is triggered.

IMHO, it seems possible that the order of the finalization is such that the output stream is destroyed before some random warning is printed in the finalizer and in that case, the only fix might be just disabling those warnings/errors.

**Comment by yuyichao** [comment]
That's very likely what happend...

```julia
julia> a = []
0-element Array{Any,1}

julia> finalizer(a, (a) -> [1:2])

julia> 
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
jl_uv_writecb() ERROR: bad file descriptor EBADF
```

**Comment by yuyichao** [comment]
and the backtrace agrees with it

```julia
Breakpoint 2, jl_breakpoint (v=0x7ffff67b2b20 <main_arena>) at builtins.c:1597
1597    {
(gdb) bt
#0  jl_breakpoint (v=0x7ffff67b2b20 <main_arena>) at builtins.c:1597
#1  0x00007ffff6b55d57 in jl_uv_writecb (req=<optimized out>, status=-9)
    at jl_uv.c:343
#2  0x00007ffff6b55f22 in jl_write (n=28, 
    str=0x1f477c0 "error in running finalizer: ", stream=0x694fd0) at jl_uv.c:391
#3  jl_vprintf (s=0x694fd0, format=<optimized out>, 
    args=args@entry=0x7fffffffd968) at jl_uv.c:412
#4  0x00007ffff6b55fc4 in jl_printf (s=<optimized out>, 
    format=format@entry=0x7ffff7575620 "error in running finalizer: ")
    at jl_uv.c:425
#5  0x00007ffff6b58d5e in run_finalizer (o=0x7ffdf46756d0, ff=0x7ffdf3ff9ff0)
    at gc.c:307
#6  0x00007ffff6b5f57c in run_finalizers () at gc.c:342
#7  jl_gc_run_all_finalizers () at gc.c:363
#8  0x00007ffff6b4542d in jl_atexit_hook () at init.c:574
#9  0x000000000040161d in main (argc=0, argv=0x7fffffffdec8) at repl.c:577
```

There's basically nothing we can do about finalization order. We can probably avoid some printing if we are in this stage to suppress the error (or the error message).

**Comment by JeffBezanson** [comment]
Presuming this goes away when the deprecation warning is fixed. Please reopen if that's not the case.
