### ISSUE TITLE
RandomFerns v0.1.0 reliably segfaults on Julia master

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#14021]
My machine
```
Julia Version 0.5.0-dev+1317
Commit 8c23dc8 (2015-11-17 02:21 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.0.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

```
$ julia test/runtests.jl
julia(93396,0x700000081000) malloc: *** error for object 0x7fd55c021208: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Segmentation fault: 11
```

And on PkgEval:
```
Julia Version 0.5.0-dev+1306
Commit aa24ee0 (2015-11-15 23:12 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
```
INFO: Testing RandomFerns
*** Error in `/home/vagrant/julia/bin/julia': malloc(): memory corruption (fast): 0x0000000003514a60 ***

signal (15): Terminated
syscall at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
uv__epoll_wait at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
uv__io_poll at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
uv_run at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
process_events at ./stream.jl:709
wait at ./task.jl:360
wait at ./task.jl:286
jl_apply_generic at /home/vagrant/julia/bin/../lib/julia/libjulia.so (unknown line)
stream_wait at ./stream.jl:59
....
```

**Comment by yuyichao** [comment]
This looks like a bug in `FunctionalData`. I don't know what it is trying to achieve but [this](https://github.com/rened/FunctionalData.jl/blob/836fb46ab8bcc8dd2c187d1de1016a6467aba06b/src/views.jl#L25) is guaranteed to break at any time.

In particular, this line write a huge value to the length field of the array which cause a following `a[:] = ...` to write to random positions.

GDB trace.
```
Hardware watchpoint 1: *(void**)0x7ffdf37bce98

Old value = (void *) 0x1
New value = (void *) 0x2f3f5b0
julia_view!_22937 () at /home/yuyichao/.julia/v0.5/FunctionalData/src/views.jl:28
28          v
(gdb) bt
#0  julia_view!_22937 ()
    at /home/yuyichao/.julia/v0.5/FunctionalData/src/views.jl:28
#1  0x00007ffdd757b041 in jlcall_view!_22937 ()
#2  0x00007ffff688382d in jl_apply (nargs=3, args=0x7fffffffcfd0, 
    f=<optimized out>) at /home/yuyichao/projects/julia/gc/debug/src/julia.h:1410
#3  jl_apply_generic (F=0x7ffdf3b3f530, args=0x7fffffffcfd0, 
    nargs=<optimized out>)
    at /home/yuyichao/projects/julia/gc/debug/src/gf.c:1920
#4  0x00007ffdd7581115 in julia_view_22933 ()
    at /home/yuyichao/.julia/v0.5/FunctionalData/src/views.jl:20
#5  0x00007ffdd758115a in jlcall_view_22933 ()
#6  0x00007ffff688382d in jl_apply (nargs=2, args=0x7fffffffd110, 
    f=<optimized out>) at /home/yuyichao/projects/julia/gc/debug/src/julia.h:1410
#7  jl_apply_generic (F=0x7ffdf3b3ee30, args=0x7fffffffd110, 
    nargs=<optimized out>)
    at /home/yuyichao/projects/julia/gc/debug/src/gf.c:1920
#8  0x00007ffdd75a61db in julia_map_22900 ()
    at /home/yuyichao/.julia/v0.5/FunctionalData/src/computing.jl:125
#9  0x00007ffff688382d in jl_apply (nargs=2, args=0x7fffffffd1f8, 
    f=<optimized out>) at /home/yuyichao/projects/julia/gc/debug/src/julia.h:1410
#10 jl_apply_generic (F=0x7ffdf2d883f0, args=0x7fffffffd1f8, 
    nargs=<optimized out>)
    at /home/yuyichao/projects/julia/gc/debug/src/gf.c:1920
#11 0x00007ffff6897393 in jl_apply (nargs=2, args=0x7fffffffd1f8, 
    f=0x7ffdf2d883f0) at /home/yuyichao/projects/julia/gc/debug/src/julia.h:1410
#12 do_call (f=f@entry=0x7ffdf2d883f0, args=args@entry=0x7ffdf3abce28, 
    nargs=nargs@entry=2, eval0=eval0@entry=0x0, locals=locals@entry=0x0, 
    nl=nl@entry=0, ngensym=0)
    at /home/yuyichao/projects/julia/gc/debug/src/interpreter.c:65
#13 0x00007ffff6896746 in eval (e=0x7ffdf415b730, locals=locals@entry=0x0, 
    nl=nl@entry=0, ngensym=ngensym@entry=0)
    at /home/yuyichao/projects/julia/gc/debug/src/interpreter.c:214
#14 0x00007ffff68972cb in jl_interpret_toplevel_expr (e=<optimized out>)
    at /home/yuyichao/projects/julia/gc/debug/src/interpreter.c:27
#15 0x00007ffff68ab93c in jl_toplevel_eval_flex (e=<optimized out>, 
    fast=fast@entry=1)
    at /home/yuyichao/projects/julia/gc/debug/src/toplevel.c:531
#16 0x00007ffff68ac62c in jl_toplevel_eval_flex (fast=1, e=<optimized out>)
    at /home/yuyichao/projects/julia/gc/debug/src/toplevel.c:577
#17 jl_parse_eval_all (
    fname=fname@entry=0x7ffdf3457940 "/home/yuyichao/.julia/v0.5/RandomFerns/test/runtests.jl", len=len@entry=55)
    at /home/yuyichao/projects/julia/gc/debug/src/toplevel.c:581
#18 0x00007ffff68ac825 in jl_load (
    fname=0x7ffdf3457940 "/home/yuyichao/.julia/v0.5/RandomFerns/test/runtests.jl", len=55) at /home/yuyichao/projects/julia/gc/debug/src/toplevel.c:621
```

At a closer look, I think it recognize julia 0.5 as 0.3 due to the version check right above. However, I'd be very surprised if this does not break any assumptions made by the GC etc.
