### ISSUE TITLE
make install doesn't work -- ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by sfchen** [JuliaLang/julia#14289]
on Mac OS X 10.10.5 

touch -c ../deps/build/julia-env/bin/sphinx-build
. ./../deps/build/julia-env/bin/activate && sphinx-build -b html -d ./_build/doctrees   /Users/shifu/github/julia/doc ./_build/html
Traceback (most recent call last):
  File "/Users/shifu/github/julia/deps/build/julia-env/bin/sphinx-build", line 11, in <module>
    sys.exit(main())
  File "/Users/shifu/github/julia/deps/build/julia-env/lib/python2.7/site-packages/sphinx/__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "/Users/shifu/github/julia/deps/build/julia-env/lib/python2.7/site-packages/sphinx/__init__.py", line 61, in build_main
    from sphinx import cmdline
  File "/Users/shifu/github/julia/deps/build/julia-env/lib/python2.7/site-packages/sphinx/cmdline.py", line 19, in <module>
    from docutils.utils import SystemMessage
  File "/Users/shifu/github/julia/deps/build/julia-env/lib/python2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "/Users/shifu/github/julia/deps/build/julia-env/lib/python2.7/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/Users/shifu/github/julia/deps/build/julia-env/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/Users/shifu/github/julia/deps/build/julia-env/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/shifu/github/julia/deps/build/julia-env/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
make[1]: *** [html] Error 1
make: *** [/Users/shifu/github/julia/doc/_build/html] Error 2

**Comment by sfchen** [comment]
Found the solution:

If you have faced the error on MacOS X, here's the quick fix - add these lines to your ~/.bashrc:

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

See https://coderwall.com/p/-k_93g/mac-os-x-valueerror-unknown-locale-utf-8-in-python
