### ISSUE TITLE
OS X build/install of 0.5 master fails with Anaconda2 python-2.7.11

### ISSUE THREAD

**Issue by protogeezer** [JuliaLang/julia#15112]
```
Julia Version 0.5.0-dev+2701
Commit a02ecac* (2016-02-16 19:24 UTC)
DEBUG build
Platform Info:
  System: Darwin (x86_64-apple-darwin15.4.0)
  CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1
```

The build works after downgrading to python 2.7.10... The problem may be deps/srccache/virtualenv-1.11 needs to be bumped to a newer version. 

The specific error:
```
ImportError: dlopen(/Users/sjbespa/work/julia/julia-0.5/build/deps/julia-env/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
```
is vexing the Conda team... it's unclear if there is more to this than updating virtualenv
Stephen

note: out of tree build to facilitate building different versions of julia (i.e. w/wo CXX)
```
cd julia/julia-0.5
git pull
cd build
make
...
docs/helpdb/Dates.jl
docs/basedocs.jl
threads.jl
threadcall.jl
/Users/sjbespa/work/julia/julia-0.5/base/precompile.jl
    LINK build/usr/lib/julia/sys.dylib
ld: warning: object file (/Users/sjbespa/work/julia/julia-0.5/build/usr/lib/julia/sys.o) was built for newer OSX version (15.4) than being linked (10.7)

et-imac-retina:build sjbespa$ sudo make install
Password:
    CC build/usr/bin/stringreplace
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ./../deps install-virtualenv
"/Users/sjbespa/anaconda2/bin/python" /Users/sjbespa/work/julia/julia-0.5/deps/srccache/virtualenv-1.11.6/virtualenv.py julia-env
New python executable in julia-env/bin/python
Installing setuptools, pip...
  Complete output from command /Users/sjbespa/work/...julia-env/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sjbespa/work/julia/julia-0.5/deps/srccache/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/__init__.py", line 9, in <module>
  File "/Users/sjbespa/work/julia/julia-0.5/deps/srccache/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/log.py", line 8, in <module>
  File "/Users/sjbespa/work/julia/julia-0.5/deps/srccache/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/backwardcompat/__init__.py", line 66, in <module>
  File "/Users/sjbespa/anaconda2/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/Users/sjbespa/anaconda2/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/Users/sjbespa/anaconda2/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/Users/sjbespa/anaconda2/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/sjbespa/anaconda2/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/sjbespa/work/julia/julia-0.5/build/deps/julia-env/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/sjbespa/work/julia/julia-0.5/build/deps/julia-env/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup

----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/Users/sjbespa/work/julia/julia-0.5/deps/srccache/virtualenv-1.11.6/virtualenv.py", line 2338, in <module>
    main()
  File "/Users/sjbespa/work/julia/julia-0.5/deps/srccache/virtualenv-1.11.6/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/Users/sjbespa/work/julia/julia-0.5/deps/srccache/virtualenv-1.11.6/virtualenv.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Users/sjbespa/work/julia/julia-0.5/deps/srccache/virtualenv-1.11.6/virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Users/sjbespa/work/julia/julia-0.5/deps/srccache/virtualenv-1.11.6/virtualenv.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/sjbespa/work/...julia-env/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
make[2]: *** [julia-env] Error 1
make[1]: *** [../deps/julia-env/bin/activate] Error 2
make: *** [/Users/sjbespa/work/julia/julia-0.5/build/doc/_build/html] Error 2
et-imac-retina:build sjbespa$ sudo make install
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ./../deps install-virtualenv
make[2]: Nothing to be done for `install-virtualenv'.
touch -c ../deps/julia-env/bin/activate
. ./../deps/julia-env/bin/activate && pip install sphinx==1.3.1 \
	              && pip install -r /Users/sjbespa/work/julia/julia-0.5/doc/requirements.txt
/bin/sh: ./../deps/julia-env/bin/activate: No such file or directory
make[1]: *** [../deps/julia-env/bin/sphinx-build] Error 1
make: *** [/Users/sjbespa/work/julia/julia-0.5/build/doc/_build/html] Error 2
```

edit: fixed markdown syntax code guards

**Comment by tkelman** [comment]
This looks like a Python problem? A point release of Python breaking an existing release of Virtualenv strikes me as really surprising. Last time I tried upgrading Virtualenv it didn't work properly on Windows, so would need some testing.

**Comment by protogeezer** [comment]
No, I don't believe that this is Python problem, and the out-of-date virtualenv could be a red-herring. Others have suggested this particular crash could be due to inconsistent python libraries and executables... That could point at the Makefile. 
What I can tell so far:
(1) I did a clean rebuild with Python 2.7.11 installed but not on the search path. That works.
(2) The build doesn't work when Anaconda Python 2.7.11 is on the search path
(3) The build does does work when Anaconda python 2.7.10 is on the search path.
(4) The Apple supplied python is 2.7.10 and resides in /usr/bin
The simplest explanation of the observations would be the make calling .../Anaconda2/bin/python with the Apple libraries on the search path. I'm not entirely clear on how to prove that. Yet anyway.
