### ISSUE TITLE
Segfault (failed GC assertion) triggered with Gallium & HackThatBase

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#16135]
(This is not ideal because it's not a simple test case, but I should report it before I change more stuff and suddenly can't reproduce.)

I'm interested in getting Gallium-debugging working for inference.jl. Presumably as with https://github.com/Keno/Gallium.jl/issues/84, this requires special care, and [HackThatBase.jl](https://github.com/ihnorton/HackThatBase.jl) seems likely to be the way to go. (At the moment, you need both https://github.com/Keno/Gallium.jl/pull/90 and https://github.com/ihnorton/HackThatBase.jl/pull/4.) However, in playing with this I was able to trigger a segfault.

``` jl
julia> versioninfo()
Julia Version 0.5.0-dev+3804
Commit 191e37d* (2016-04-30 01:18 UTC)
DEBUG build
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)
```

(note it's a debug build)

Test file contents ("ambig.jl"):

``` jl
 foo(x, y) = 1
 foo(x::Integer, y) = 2
 foo(x, y::Integer) = 3

function bar(x, y)
    # Do something complicated to make sure this gets inferred
    A = rand(20, 30)
    c = cumsum(A, 1)
    foo(x, y)
    c
end
```

I also have an `inference_hacked.jl` in `base/`, with this diff:

``` diff
$ diff inference.jl inference_hacked.jl
3412c3412
< precompile(methods(typeinf_edge).defs.sig)

---
> # precompile(methods(typeinf_edge).defs.sig)
3421c3421
< ccall(:jl_set_typeinf_func, Void, (Any,), typeinf_ext)

---
> # ccall(:jl_set_typeinf_func, Void, (Any,), typeinf_ext)
```

OK, now the demo:

``` jl
julia> using HackThatBase

julia> include("/tmp/tim/ambig.jl")
WARNING: New definition 
    foo(Any, Integer) at /tmp/tim/ambig.jl:3
is ambiguous with: 
    foo(Integer, Any) at /tmp/tim/ambig.jl:2.
To fix, define 
    foo(Integer, Integer)
before the new definition.
bar (generic function with 1 method)

julia> args = lminfo(bar, (Int,Int))
(Main.bar at /tmp/tim/ambig.jl:7,Tuple{#bar,Int64,Int64},svec())

julia> @hack W inference_hacked
W

julia> result = W.typeinf_uncached(args...)
(LambdaInfo for bar
:(begin  # /tmp/tim/ambig.jl, line 7: # random.jl, line 209: # random.jl, line 208: # random.jl, line 276: # random.jl, line 279:
        GenSym(1) = (top(ccall))(:jl_new_array,(top(apply_type))(Core.Array,Float64,2)::Type{Array{Float64,2}},(top(svec))(Core.Any,Core.Any)::SimpleVector,Array{Float64,2},0,(Base.tuple)(20,30)::Tuple{Int64,Int64},0)::Array{Float64,2} # random.jl, line 327:
        A = (Base.Random.rand!)(Base.Random.GLOBAL_RNG,GenSym(1),(Base.arraylen)(GenSym(1))::Int64,Base.Random.CloseOpen)::Array{Float64,2} # /tmp/tim/ambig.jl, line 8: # multidimensional.jl, line 530: # array.jl, line 128:
        GenSym(3) = (Base.arraysize)(A,1)::Int64
        GenSym(2) = (Base.arraysize)(A,2)::Int64 # boot.jl, line 322:
        c = (Base.cumsum!)((top(ccall))(:jl_alloc_array_2d,(top(apply_type))(Core.Array,Float64,2)::Type{Array{Float64,2}},(top(svec))(Core.Any,Core.Int,Core.Int)::SimpleVector,Array{Float64,2},0,GenSym(3),0,GenSym(2),0)::Array{Float64,2},A,1)::Array{Float64,2} # /tmp/tim/ambig.jl, line 9:
        2 # /tmp/tim/ambig.jl, line 10:
        return c
    end::Array{Float64,2}),Array{Float64,2},true)

julia> using Gallium
INFO: Recompiling stale cache file /home/tim/.julia/lib/v0.5/Gallium.ji for module Gallium.

julia> breakpoint(W.inlineable)
Locations (+: active, -: inactive, *: source):
 + inlineable(f, ft, e::Expr, atypes::Array{Any,1}, sv::W.InferenceState, enclosing::LambdaInfo) at none:11
 * Any matching method added to W.#inlineable
 * Any matching specialization of inlineable(f, ft, e, atypes, sv, enclosing) at none:11


julia> result = W.typeinf_uncached(args...)
julia: /home/tim/src/julia-0.5/src/gc.c:617: find_region: Assertion `maybe && "find_region failed"' failed.

signal (6): Aborted
while loading no file, in expression starting on line 0
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fa80da63b85)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
find_region at /home/tim/src/julia-0.5/src/gc.c:617
page_metadata at /home/tim/src/julia-0.5/src/gc.c:623
gc_setmark_pool at /home/tim/src/julia-0.5/src/gc.c:759
gc_setmark at /home/tim/src/julia-0.5/src/gc.c:787
push_root at /home/tim/src/julia-0.5/src/gc.c:1892
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1908
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1855
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1908
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1908
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1855
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1908
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1908
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1908
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1908
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1908
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1796
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1908
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1796
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1908
gc_push_root at /home/tim/src/julia-0.5/src/gc.c:1630
push_root at /home/tim/src/julia-0.5/src/gc.c:1796
_jl_gc_collect at /home/tim/src/julia-0.5/src/gc.c:2136
jl_gc_collect at /home/tim/src/julia-0.5/src/gc.c:2350
__pool_alloc at /home/tim/src/julia-0.5/src/gc.c:1188
_pool_alloc at /home/tim/src/julia-0.5/src/gc.c:1241
jl_gc_alloc_1w at /home/tim/src/julia-0.5/src/gc.c:2456
Type at ./boot.jl:245
jl_call_method_internal at /home/tim/src/julia-0.5/src/julia_internal.h:76
jl_apply_generic at /home/tim/src/julia-0.5/src/gf.c:1519
#76 at ./<no file>:4294967295
unknown function (ip: 0x7fa607d5ee6d)
jl_call_method_internal at /home/tim/src/julia-0.5/src/julia_internal.h:76
jl_apply_generic at /home/tim/src/julia-0.5/src/gf.c:1519
inlining_pass at ./none:114
inlining_pass at ./none:40
unknown function (ip: 0x7fa607d67951)
jl_call_method_internal at /home/tim/src/julia-0.5/src/julia_internal.h:76
jl_apply_generic at /home/tim/src/julia-0.5/src/gf.c:1519
inlining_pass! at ./none:8
finish at ./none:35
typeinf_frame at ./none:199
typeinf_loop at ./none:21
unknown function (ip: 0x7fa60803e952)
jl_call_method_internal at /home/tim/src/julia-0.5/src/julia_internal.h:76
jl_apply_generic at /home/tim/src/julia-0.5/src/gf.c:1519
typeinf_edge at ./none:109
unknown function (ip: 0x7fa6080613b8)
jl_call_method_internal at /home/tim/src/julia-0.5/src/julia_internal.h:76
jl_apply_generic at /home/tim/src/julia-0.5/src/gf.c:1519
unknown function (ip: 0x7fa5f97010f1)
unknown function (ip: 0x7fa5f9701181)
jl_call_method_internal at /home/tim/src/julia-0.5/src/julia_internal.h:76
jl_apply_generic at /home/tim/src/julia-0.5/src/gf.c:1519
jl_apply at /home/tim/src/julia-0.5/src/julia.h:1342
jl_f__apply at /home/tim/src/julia-0.5/src/builtins.c:505
jl_call_method_internal at /home/tim/src/julia-0.5/src/julia_internal.h:76
jl_apply_generic at /home/tim/src/julia-0.5/src/gf.c:1519
do_call at /home/tim/src/julia-0.5/src/interpreter.c:58
eval at /home/tim/src/julia-0.5/src/interpreter.c:181
eval at /home/tim/src/julia-0.5/src/interpreter.c:185
eval_body at /home/tim/src/julia-0.5/src/interpreter.c:516
jl_interpret_toplevel_thunk at /home/tim/src/julia-0.5/src/interpreter.c:536
jl_toplevel_eval_flex at /home/tim/src/julia-0.5/src/toplevel.c:549
jl_toplevel_eval at /home/tim/src/julia-0.5/src/toplevel.c:557
jl_toplevel_eval_in_warn at /home/tim/src/julia-0.5/src/builtins.c:547
jl_toplevel_eval_in at /home/tim/src/julia-0.5/src/builtins.c:514
eval at ./boot.jl:236
unknown function (ip: 0x7fa80a476850)
jl_call_method_internal at /home/tim/src/julia-0.5/src/julia_internal.h:76
jl_apply_generic at /home/tim/src/julia-0.5/src/gf.c:1519
[inline] at ./REPL.jl:3
eval_user_input at ./REPL.jl:62
unknown function (ip: 0x7fa6086d75b6)
jl_call_method_internal at /home/tim/src/julia-0.5/src/julia_internal.h:76
jl_apply_generic at /home/tim/src/julia-0.5/src/gf.c:1519
[inline] at ./REPL.jl:92
#1 at ./event.jl:46
unknown function (ip: 0x7fa60873f52f)
jl_call_method_internal at /home/tim/src/julia-0.5/src/julia_internal.h:76
jl_apply_generic at /home/tim/src/julia-0.5/src/gf.c:1519
jl_apply at /home/tim/src/julia-0.5/src/julia.h:1342
start_task at /home/tim/src/julia-0.5/src/task.c:249
unknown function (ip: 0xffffffffffffffff)
Allocations: 30736408 (Pool: 30732474; Big: 3934); GC: 35
Aborted (core dumped)
```

**Comment by timholy** [comment]
I paused there in gdb and got this:
```
(gdb) call jl_(ptr)
<?#0x7fffffffa230::W.Const(val=Base.Random.#rand())>
(gdb) 
```

**Comment by yuyichao** [comment]
What are the Gallium and HackThatBase commit you reproduce this with?

**Comment by yuyichao** [comment]
OK, the issue seems to be that someone called `unsafe_pointer_to_objref` with a stack address.

Backtrace

```
#0  0x00007f5d493e20e0 in jlcall_unsafe_pointer_to_objref_54394 ()
#1  0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d787ee800, 
    args=0x7ffe58c6c180, nargs=2)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#2  0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c6c180, nargs=2)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#3  0x00007f5d495c338b in julia_#28_53992 (RC=...)
    at /home/yuyichao/.julia/v0.5/Gallium/src/Gallium.jl:348
#4  0x00007f5d495c4a87 in julia_rec_backtrace_54027 (callback=..., RC=..., 
    session=..., modules=...)
    at /home/yuyichao/.julia/v0.5/Gallium/src/Gallium.jl:205
#5  0x00007f5d495b6096 in julia_rec_backtrace_hook_53991 (callback=..., RC=..., 
    session=..., modules=...)
    at /home/yuyichao/.julia/v0.5/Gallium/src/Gallium.jl:217
#6  0x00007f5d495b60ee in jlcall_rec_backtrace_hook_53991 ()
#7  0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d70a8cac0, 
    args=0x7ffe58c6c568, nargs=5)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#8  0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c6c568, nargs=5)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#9  0x00007f5d495c722f in julia_#stackwalk#27_53990 (fromhook=<optimized out>, 
    rich_c=<optimized out>, RC=..., session=..., modules=...)
    at /home/yuyichao/.julia/v0.5/Gallium/src/Gallium.jl:233
#10 0x00007f5d495c72f0 in jlcall_#stackwalk#27_53990 ()
#11 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d661ce260, 
    args=0x7ffe58c6c780, nargs=7)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#12 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c6c780, nargs=7)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#13 0x00007f5d59eee364 in julia_#stackwalk_53984 ()
#14 0x00007f5d59eee5d2 in jlcall_#stackwalk_53984 ()
#15 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d64600760, 
    args=0x7ffe58c6ccf8, nargs=6)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#16 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c6ccf8, nargs=6)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#17 0x00007f5d59ef2820 in julia_breakpoint_hit_53980 (hook=..., RC=...)
#18 julia_breakpoint_hit_53980 (hook=..., RC=...)
    at /home/yuyichao/.julia/v0.5/Gallium/src/Gallium.jl:405
#19 0x00007f5d59ef3bc9 in jlcall_breakpoint_hit_53980 ()
#20 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d64235330, 
    args=0x7ffe58c6d0f0, nargs=3)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#21 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c6d0f0, nargs=3)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
---Type <return> to continue, or q <return> to quit---
#22 0x00007f5d495f6fc9 in julia__callback_53825 (x=<optimized out>)
    at /home/yuyichao/.julia/v0.5/Gallium/src/Hooking/Hooking.jl:150
#23 0x00007f5d495f77ba in julia_callback_53824 (x=140730387845648)
    at /home/yuyichao/.julia/v0.5/Gallium/src/Hooking/Hooking.jl:184
#24 0x00007f5d495f7860 in jlcapi_callback_53827 ()
#25 0x00007f5d5a27200e in julia_inlineable_53640 (f=0x7f5d6020f8d0, 
    ft=0x7f5d7bee2510, e=..., atypes=0x0, sv=..., enclosing=0x7f5d7bee2530)
#26 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d61d3cb50, 
    args=0x7ffe58c6dd20, nargs=7)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#27 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c6dd20, nargs=7)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#28 0x00007f5d5a2838ab in julia_inlining_pass_53636 (e=..., sv=..., 
    linfo=0x7f5d64234910) at none:114
#29 0x00007f5d5a28216f in julia_inlining_pass_53636 (e=..., sv=..., 
    linfo=0x7f5d64234910) at none:40
#30 0x00007f5d5a285962 in jlcall_inlining_pass_53636 ()
#31 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d61d3c5b0, 
    args=0x7ffe58c6eb30, nargs=4)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#32 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c6eb30, nargs=4)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#33 0x00007f5d5a70f7f4 in julia_inlining_pass!_53565 (linfo=0x7f5d64234910, 
    sv=...) at none:8
#34 0x00007f5d5a715525 in julia_finish_53563 (me=...) at none:35
#35 0x00007f5d5a7185a7 in julia_typeinf_frame_53543 (frame=...) at none:199
#36 0x00007f5d5a70b467 in julia_typeinf_loop_53542 (frame=...) at none:21
#37 0x00007f5d5a70b953 in jlcall_typeinf_loop_53542 ()
#38 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d60fc54e0, 
    args=0x7ffe58c6fdb0, nargs=2)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#39 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c6fdb0, nargs=2)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#40 0x00007f5d5a72e088 in julia_typeinf_edge_53531 (method=..., 
    atypes=0x7f5d5f4c4190, sparams=0x7f5d5a84c010, needtree=0, optimize=0, 
    cached=<optimized out>, caller=...) at none:109
#41 0x00007f5d5a72e3d9 in jlcall_typeinf_edge_53531 ()
#42 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d60d0d2a0, 
    args=0x7ffe58c6ff28, nargs=8)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#43 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c6ff28, nargs=8)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#44 0x00007f5d5a1a90f2 in julia_typeinf_uncached_53752 ()
#45 0x00007f5d5a1a9182 in jlcall_typeinf_uncached_53752 ()
#46 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d611df4f0, 
---Type <return> to continue, or q <return> to quit---
    args=0x7ffe58c700f0, nargs=4)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#47 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c700f0, nargs=4)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#48 0x00007f5f61b43f7f in jl_apply (args=0x7ffe58c700f0, nargs=4)
    at /home/yuyichao/projects/julia/master/src/julia.h:1342
#49 0x00007f5f61b462e7 in jl_f__apply (F=0x7f5d5ae3bab8, args=0x7ffe58c70318, 
    nargs=2) at /home/yuyichao/projects/julia/master/src/builtins.c:505
#50 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d5af42a40, 
    args=0x7ffe58c70310, nargs=3)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#51 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c70310, nargs=3)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#52 0x00007f5f61b4f097 in do_call (args=0x7f5d640937e0, nargs=3, 
    locals=0x7ffe58c70cf0, lam=0x7f5d64234880)
    at /home/yuyichao/projects/julia/master/src/interpreter.c:58
#53 0x00007f5f61b4faa5 in eval (e=0x7f5d6020f810, locals=0x7ffe58c70cf0, 
    lam=0x7f5d64234880)
    at /home/yuyichao/projects/julia/master/src/interpreter.c:181
#54 0x00007f5f61b4faff in eval (e=0x7f5d6020f7f0, locals=0x7ffe58c70cf0, 
    lam=0x7f5d64234880)
    at /home/yuyichao/projects/julia/master/src/interpreter.c:185
#55 0x00007f5f61b51847 in eval_body (stmts=0x7f5d64093730, 
    locals=0x7ffe58c70cf0, lam=0x7f5d64234880, start=0, toplevel=1)
    at /home/yuyichao/projects/julia/master/src/interpreter.c:516
#56 0x00007f5f61b519ec in jl_interpret_toplevel_thunk (lam=0x7f5d64234880)
    at /home/yuyichao/projects/julia/master/src/interpreter.c:536
#57 0x00007f5f61b70772 in jl_toplevel_eval_flex (e=0x7f5d6020f790, fast=1)
    at /home/yuyichao/projects/julia/master/src/toplevel.c:549
#58 0x00007f5f61b420ba in jl_parse_eval_all (
    fname=0x7f5d5ef437d0 "/home/yuyichao/projects/julia/master/script.jl", 
    len=46, content=0x0, contentlen=0)
    at /home/yuyichao/projects/julia/master/src/ast.c:791
#59 0x00007f5f61b708d2 in jl_load (
    fname=0x7f5d5ef437d0 "/home/yuyichao/projects/julia/master/script.jl", 
    len=46) at /home/yuyichao/projects/julia/master/src/toplevel.c:573
#60 0x00007f5f61b70923 in jl_load_ (str=0x7f5d5aa633b0)
    at /home/yuyichao/projects/julia/master/src/toplevel.c:579
#61 0x00007f5f5c426131 in julia_include_900 (fname=...) at boot.jl:233
#62 0x00007f5f5c42619d in jlcall_include_900 ()
   from /home/yuyichao/projects/julia/master/usr/lib/julia/sys-debug.so
#63 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d5a838490, 
    args=0x7ffe58c71470, nargs=2)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#64 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c71470, nargs=2)
---Type <return> to continue, or q <return> to quit---
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#65 0x00007f5f5c629f54 in julia_include_from_node1_19776 (_path=...)
    at loading.jl:426
#66 0x00007f5f5c62a23d in jlcall_include_from_node1_19776 ()
   from /home/yuyichao/projects/julia/master/usr/lib/julia/sys-debug.so
#67 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d5da84370, 
    args=0x7ffe58c71800, nargs=2)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#68 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c71800, nargs=2)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#69 0x00007f5f5c61e17a in julia_process_options_19402 (opts=...) at client.jl:263
#70 0x00007f5f5c6221b0 in julia__start_19395 () at client.jl:319
#71 0x00007f5f5c622fa5 in jlcall.start_19395 ()
   from /home/yuyichao/projects/julia/master/usr/lib/julia/sys-debug.so
#72 0x00007f5f61b3419d in jl_call_method_internal (meth=0x7f5d5df1bb20, 
    args=0x7ffe58c71f90, nargs=1)
    at /home/yuyichao/projects/julia/master/src/julia_internal.h:76
#73 0x00007f5f61b39836 in jl_apply_generic (args=0x7ffe58c71f90, nargs=1)
    at /home/yuyichao/projects/julia/master/src/gf.c:1519
#74 0x0000000000401b16 in jl_apply (args=0x7ffe58c71f90, nargs=1)
    at /home/yuyichao/projects/julia/master/ui/../src/julia.h:1342
#75 0x0000000000402fe1 in true_main (argc=1, argv=0x7ffe58c721f8)
    at /home/yuyichao/projects/julia/master/ui/repl.c:544
#76 0x0000000000403396 in main (argc=1, argv=0x7ffe58c721f8)
    at /home/yuyichao/projects/julia/master/ui/repl.c:672
```

@Keno

**Comment by Keno** [comment]
That's the kind of thing I might do. I'll take a look at it, but won't get to it until next week.

**Comment by yuyichao** [comment]
Also it seems that at least HackThatBase is broken now on master...

**Comment by timholy** [comment]
See https://github.com/ihnorton/HackThatBase.jl/pull/5
