### ISSUE TITLE
0.5: Segmentation fault in gc_enable call on linux

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#16624]
The Travis tests for BandedMatrices.jl fail in 0.5 on linux when calling `gc_enable(true)`:

https://travis-ci.org/ApproxFun/BandedMatrices.jl/jobs/133542136

It's possible that there is a pointer arithmetic bug in the package that gets hit, though the other three test setups pass.

The version info is

```julia
Julia Version 0.5.0-dev+4370
Commit 758aebc (2016-05-27 21:34 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```

Here is the error dump:

```julia
signal (11): Segmentation fault
while loading /home/travis/.julia/v0.5/BandedMatrices/test/runtests.jl, in expression starting on line 127
push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1251
gc_push_root at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1116
_jl_gc_collect at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:1619
__pool_alloc at /home/centos/buildbot/slave/package_tarball64/build/src/gc.c:676
newstruct at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:62
scm_to_julia_ at /home/centos/buildbot/slave/package_tarball64/build/src/ast.c:506
scm_to_julia at /home/centos/buildbot/slave/package_tarball64/build/src/ast.c:379
jl_parse_eval_all at /home/centos/buildbot/slave/package_tarball64/build/src/ast.c:769
jl_load at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:585
include_from_node1 at ./loading.jl:426
unknown function (ip: 0x7ff7472ed74c)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:88
process_options at ./client.jl:266
_start at ./client.jl:322
unknown function (ip: 0x7ff747328ae4)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:88
jl_apply at /home/centos/buildbot/slave/package_tarball64/build/ui/../src/julia.h:1388
main at /home/centos/buildbot/slave/package_tarball64/build/ui/repl.c:671
unknown function (ip: 0x7ff74a6ca7ec)
unknown function (ip: 0x401840)
Allocations: 88189337 (Pool: 88177386; Big: 11951); GC: 68
```

**Comment by yuyichao** [comment]
This is a package error. Backtrace for (at least one of the) invalid write.
```
(rr) bt
#0  dscal_k_HASWELL (n=5, dummy0=<optimized out>, dummy1=<optimized out>, 
    da=<optimized out>, x=0x7fbff1a04050, inc_x=1, y=0x0, inc_y=0, dummy=0x0, 
    dummy2=0) at ../kernel/x86_64/dscal.c:224
#1  0x00007fbfe9f82b0d in dgbmv_ (TRANS=<optimized out>, M=<optimized out>, 
    N=<optimized out>, KU=<optimized out>, KL=<optimized out>, 
    ALPHA=<optimized out>, a=0x7fbff192bdd0, LDA=0x7ffeb32f4a94, 
    x=0x7fbff192be30, INCX=0x7ffeb32f4a90, BETA=0x7ffeb32f4a88, 
    y=0x7fbff1a04050, INCY=0x7ffeb32f4a84) at gbmv.c:216
#2  0x00007fbfecc40356 in julia_gbmv!_50485 (trans=<optimized out>, 
    m=<optimized out>, kl=<optimized out>, ku=<optimized out>, alpha=0, 
    A=<optimized out>, n=<optimized out>, st=<optimized out>, x=<optimized out>, 
    beta=0, y=140462369292368)
    at /home/yuyichao/projects/tmp/BandedMatrices.jl/src/blas.jl:30
#3  0x00007fbfecc41020 in julia_gbmm!_50484 (α=4607182418800017408, A=..., 
    B=..., β=0, C=...)
    at /home/yuyichao/projects/tmp/BandedMatrices.jl/src/blas.jl:109
#4  0x00007fbfecc4016c in julia_*_50483 (A=..., B=...)
    at /home/yuyichao/projects/tmp/BandedMatrices.jl/src/BandedMatrices.jl:402
#5  0x00007fbfecc4020e in jlcall_*_50483 ()
#6  0x00007fc1f4557a9f in jl_call_method_internal (nargs=3, args=0x7ffeb32f5040, 
    meth=0x7fbff346fa90)
---Type <return> to continue, or q <return> to quit---
   nal.h:88                                                                       
#7  jl_apply_generic (args=0x7ffeb32f5040, nargs=<optimized out>)                 
    at /home/yuyichao/projects/julia/gc/debug/src/gf.c:1595                       
#8  0x00007fbfdc4f2700 in macro expansion ()                                      
    at /home/yuyichao/projects/tmp/BandedMatrices.jl/test/runtests.jl:108         
#9  julia_anonymous_50634 () at <missing>:65535                                   
#10 0x00007fbfdc4f29d0 in jlcall_anonymous_50634 ()                               
#11 0x00007fc1f4584321 in jl_call_method_internal (nargs=1, args=0x7ffeb32f5208,  
    meth=0x7fbff4499450)                                                          
    at /home/yuyichao/projects/julia/gc/debug/src/julia_internal.h:88             
#12 jl_toplevel_eval_flex (e=<optimized out>, fast=<optimized out>)               
    at /home/yuyichao/projects/julia/gc/debug/src/toplevel.c:556                  
#13 0x00007fc1f4584405 in jl_toplevel_eval_flex (e=<optimized out>,               
    fast=fast@entry=1)                                                            
    at /home/yuyichao/projects/julia/gc/debug/src/toplevel.c:434                  
#14 0x00007fc1f4562221 in jl_parse_eval_all (                                     
    fname=fname@entry=0x7fbff1a24710 "/home/yuyichao/projects/tmp/BandedMatrices.jl/test/runtests.jl", len=len@entry=62, content=content@entry=0x0,                 
    contentlen=contentlen@entry=0)                                                
    at /home/yuyichao/projects/julia/gc/debug/src/ast.c:780                       
#15 0x00007fc1f4584cbf in jl_load (                                               
    fname=0x7fbff1a24710 "/home/yuyichao/projects/tmp/BandedMatrices.jl/test/runtests.jl", len=62) at /home/yuyichao/projects/julia/gc/debug/src/toplevel.c:585     
#16 0x00007fc1ef25e41c in julia_include_from_node1_18472 (_path=...)              
    at loading.jl:426
#17 0x00007fc1ef25e6bd in jlcall_include_from_node1_18472 ()
   from /home/yuyichao/projects/julia/gc/debug/usr/lib/julia/sys.so
#18 0x00007fc1f4557a9f in jl_call_method_internal (nargs=2, args=0x7ffeb32f59a8, 
    meth=0x7fbff06112a0)
    at /home/yuyichao/projects/julia/gc/debug/src/julia_internal.h:88
#19 jl_apply_generic (args=0x7ffeb32f59a8, nargs=<optimized out>)
    at /home/yuyichao/projects/julia/gc/debug/src/gf.c:1595
#20 0x00007fc1ef294b3d in julia_process_options_19473 (opts=...) at client.jl:266
#21 0x00007fc1ef298688 in julia__start_19466 () at client.jl:322
#22 0x00007fc1ef2993e5 in jlcall.start_19466 ()
   from /home/yuyichao/projects/julia/gc/debug/usr/lib/julia/sys.so
#23 0x00007fc1f4557a9f in jl_call_method_internal (nargs=1, args=0x7ffeb32f5f80, 
    meth=0x7fbff0d5a1d0)
    at /home/yuyichao/projects/julia/gc/debug/src/julia_internal.h:88
#24 jl_apply_generic (args=args@entry=0x7ffeb32f5f80, nargs=nargs@entry=1)
    at /home/yuyichao/projects/julia/gc/debug/src/gf.c:1595
#25 0x0000000000401bf6 in jl_apply (nargs=1, args=0x7ffeb32f5f80)
    at /home/yuyichao/projects/julia/gc/debug/ui/../src/julia.h:1388
#26 true_main (argc=1, argv=0x7ffeb32f61f8)
    at /home/yuyichao/projects/julia/gc/debug/ui/repl.c:543
---Type <return> to continue, or q <return> to quit---
#27 0x000000000040167b in main (argc=<optimized out>, argv=<optimized out>)
    at /home/yuyichao/projects/julia/gc/debug/ui/repl.c:671
```

Note that the GC is very forgiving so it is totally possible that oob write doesn't generate a segfault all the time.

**Comment by yuyichao** [comment]
Also note that the segfault is much more reproducible if you don't disable the GC. (which I assume you disable to get more consistent benchmark result, it is never safe to disable GC to fix a otherwise segfaulting code).

The backtrace is obtained by watching the segfaulting address (or more precisely, where that address is loaded from) in reverse-execution in rr. Similar effect can be achieved with ASLR off in forward execution.

**Comment by dlfivefifty** [comment]
Thanks for having a look, I’ve managed to reproduce the seg fault on my own machine so can hopefully debug it.

Sorry for wasting your time.

Sheehan
