### ISSUE TITLE
Segfault in ARM when throwing exception

### ISSUE THREAD

**Issue by aviks** [JuliaLang/julia#23732]
Julia 0.6 on Raspbian Stretch 32 bit, using system LLVM

```
(gdb) run
Starting program: /usr/bin/julia 
warning: Could not find DWO CU APInt-C.dwo(0x642e170312feebd4) referenced by CU at offset 0x9398c [in module /usr/bin/../lib/libjulia.so.0.6]
warning: Could not find DWO CU runtime_ccall.dwo(0x8e0a095975cbfa63) referenced by CU at offset 0xa0739 [in module /usr/bin/../lib/libjulia.so.0.6]
warning: Could not find DWO CU codegen.dwo(0xd355432adc00f1e4) referenced by CU at offset 0xfb525 [in module /usr/bin/../lib/libjulia.so.0.6]
warning: Could not find DWO CU jitlayers.dwo(0xfd324411709f9280) referenced by CU at offset 0xfb555 [in module /usr/bin/../lib/libjulia.so.0.6]
warning: Could not find DWO CU disasm.dwo(0x1e6eaa17eb383550) referenced by CU at offset 0xfb585 [in module /usr/bin/../lib/libjulia.so.0.6]
warning: Could not find DWO CU debuginfo.dwo(0x8e38a4e933925cda) referenced by CU at offset 0xfb5b5 [in module /usr/bin/../lib/libjulia.so.0.6]
warning: Could not find DWO CU llvm-simdloop.dwo(0x9e2b806584d5b911) referenced by CU at offset 0xfb5e5 [in module /usr/bin/../lib/libjulia.so.0.6]
warning: Could not find DWO CU llvm-ptls.dwo(0x8f6358ae3bb2666c) referenced by CU at offset 0xfb615 [in module /usr/bin/../lib/libjulia.so.0.6]
warning: Could not find DWO CU llvm-gcroot.dwo(0x90d9822d1f23fb97) referenced by CU at offset 0xfb645 [in module /usr/bin/../lib/libjulia.so.0.6]
warning: Could not find DWO CU cgmemmgr.dwo(0x64e33a70f65fa723) referenced by CU at offset 0xfb675 [in module /usr/bin/../lib/libjulia.so.0.6]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x74028740 (LWP 887)]
[New Thread 0x6c7a2740 (LWP 888)]
[New Thread 0x6bfa2740 (LWP 889)]
[New Thread 0x6b7a2740 (LWP 890)]
warning: Could not find DWO CU jitlayers.dwo(0xfd324411709f9280) referenced by CU at offset 0xfb555 [in module /usr/bin/../lib/libjulia.so.0.6]
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  arm-linux-gnueabihf

julia> error()

Thread 1 "julia" received signal SIGSEGV, Segmentation fault.
0x756307c4 in void std::vector<std::pair<unsigned long long, unsigned long long>, std::allocator<std::pair<unsigned long long, unsigned long long> > >::_M_range_insert<__gnu_cxx::__normal_iterator<std::pair<unsigned long long, unsigned long long> const*, std::vector<std::pair<unsigned long long, unsigned long long>, std::allocator<std::pair<unsigned long long, unsigned long long> > > > >(__gnu_cxx::__normal_iterator<std::pair<unsigned long long, unsigned long long>*, std::vector<std::pair<unsigned long long, unsigned long long>, std::allocator<std::pair<unsigned long long, unsigned long long> > > >, __gnu_cxx::__normal_iterator<std::pair<unsigned long long, unsigned long long> const*, std::vector<std::pair<unsigned long long, unsigned long long>, std::allocator<std::pair<unsigned long long, unsigned long long> > > >, __gnu_cxx::__normal_iterator<std::pair<unsigned long long, unsigned long long> const*, std::vector<std::pair<unsigned long long, unsigned long long>, std::allocator<std::pair<unsigned long long, unsigned long long> > > >, std::forward_iterator_tag) ()
   from /usr/lib/arm-linux-gnueabihf/libLLVM-3.9.so.1
(gdb) bt
#0  0x756307c4 in void std::vector<std::pair<unsigned long long, unsigned long long>, std::allocator<std::pair<unsigned long long, unsigned long long> > >::_M_range_insert<__gnu_cxx::__normal_iterator<std::pair<unsigned long long, unsigned long long> const*, std::vector<std::pair<unsigned long long, unsigned long long>, std::allocator<std::pair<unsigned long long, unsigned long long> > > > >(__gnu_cxx::__normal_iterator<std::pair<unsigned long long, unsigned long long>*, std::vector<std::pair<unsigned long long, unsigned long long>, std::allocator<std::pair<unsigned long long, unsigned long long> > > >, __gnu_cxx::__normal_iterator<std::pair<unsigned long long, unsigned long long> const*, std::vector<std::pair<unsigned long long, unsigned long long>, std::allocator<std::pair<unsigned long long, unsigned long long> > > >, __gnu_cxx::__normal_iterator<std::pair<unsigned long long, unsigned long long> const*, std::vector<std::pair<unsigned long long, unsigned long long>, std::allocator<std::pair<unsigned long long, unsigned long long> > > >, std::forward_iterator_tag) ()
   from /usr/lib/arm-linux-gnueabihf/libLLVM-3.9.so.1
#1  0x7563a8b0 in llvm::DWARFUnit::collectAddressRanges(std::vector<std::pair<unsigned long long, unsigned long long>, std::allocator<std::pair<unsigned long long, unsigned long long> > >&) ()
   from /usr/lib/arm-linux-gnueabihf/libLLVM-3.9.so.1
#2  0x7562b15c in llvm::DWARFDebugAranges::generate(llvm::DWARFContext*) ()
   from /usr/lib/arm-linux-gnueabihf/libLLVM-3.9.so.1
#3  0x756200f0 in llvm::DWARFContext::getDebugAranges() ()
   from /usr/lib/arm-linux-gnueabihf/libLLVM-3.9.so.1
---Type <return> to continue, or q <return> to quit---
#4  0x756207e0 in llvm::DWARFContext::getCompileUnitForAddress(unsigned long long) () from /usr/lib/arm-linux-gnueabihf/libLLVM-3.9.so.1
#5  0x75620da0 in llvm::DWARFContext::getInliningInfoForAddress(unsigned long long, llvm::DILineInfoSpecifier) ()
   from /usr/lib/arm-linux-gnueabihf/libLLVM-3.9.so.1
warning: Could not find DWO CU debuginfo.dwo(0x8e38a4e933925cda) referenced by CU at offset 0xfb5b5 [in module /usr/bin/../lib/libjulia.so.0.6]
#6  0x76e1a7f4 in lookup_pointer(llvm::DIContext*, jl_frame_t**, unsigned int, int, int) [clone .part.134] ()
    at /home/pi/julia-raspbian/julia/src/debuginfo.cpp:774
#7  0x76e1eca4 in jl_getFunctionInfo ()
    at /home/pi/julia-raspbian/julia/src/debuginfo.cpp:1543
#8  0x76d9d6f4 in jl_lookup_code_address (
    ip=0x6612d22b <japi1_error_63508+190>, skipC=0)
    at /home/pi/julia-raspbian/julia/src/stackwalk.c:348
#9  0x71a8ec10 in julia_lookup_18866 () at stacktraces.jl:125
#10 0x71abb6cc in julia_collect_to!_19774 () at array.jl:474
#11 0x71abb88c in julia__collect_19772 () at array.jl:455
#12 0x71abc534 in julia_stacktrace_19776 () at stacktraces.jl:151
#13 0x6612dc84 in julia_display_error_63516 () at client.jl:126
#14 0x6612e040 in jlcall_display_error_63515 ()
#15 0x76d58d10 in jl_call_fptr_internal (fptr=0x7effc854, fptr=0x7effc854, 
    nargs=4, args=0x7effc8a0, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:339
#16 jl_call_method_internal (nargs=4, args=0x7effc8a0, meth=<optimized out>)
---Type <return> to continue, or q <return> to quit---
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:358
#17 jl_apply_generic (args=args@entry=0x7effc8a0, nargs=nargs@entry=4)
    at /home/pi/julia-raspbian/julia/src/gf.c:1933
#18 0x76d6e1e8 in do_call (args=args@entry=0x6e164110, nargs=nargs@entry=4, 
    s=s@entry=0x0) at /home/pi/julia-raspbian/julia/src/interpreter.c:75
#19 0x76d6d1dc in eval (e=e@entry=0x6e1537d0, s=s@entry=0x0)
    at /home/pi/julia-raspbian/julia/src/interpreter.c:242
#20 0x76d6eda0 in eval_body (stmts=stmts@entry=0x6e164190, s=s@entry=0x0, 
    toplevel=1, start=0) at /home/pi/julia-raspbian/julia/src/interpreter.c:539
#21 0x76d6f100 in jl_toplevel_eval_body (stmts=0x6e164190)
    at /home/pi/julia-raspbian/julia/src/interpreter.c:511

#22 0x76d85b5c in jl_toplevel_eval_flex (e=e@entry=0x6e1537f0, 
    expanded=expanded@entry=0, fast=1)
    at /home/pi/julia-raspbian/julia/src/toplevel.c:571
#23 0x76d85898 in jl_toplevel_eval (v=v@entry=0x6e1537f0)
    at /home/pi/julia-raspbian/julia/src/toplevel.c:600
#24 0x76d67518 in jl_toplevel_eval_in (m=0x70060010, ex=0x6e1537f0)
    at /home/pi/julia-raspbian/julia/src/builtins.c:496
#25 0x71a517a4 in julia_eval_17834 () at boot.jl:235
#26 0x71a517bc in jlcall_eval_17833 () from /usr/lib/julia/sys.so
#27 0x76d58d10 in jl_call_fptr_internal (fptr=0x7effd35c, fptr=0x7effd35c, 
    nargs=3, args=0x7effd3e4, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:339
---Type <return> to continue, or q <return> to quit---
#28 jl_call_method_internal (nargs=3, args=0x7effd3e4, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:358
#29 jl_apply_generic (args=0x7effd3e4, nargs=3)
    at /home/pi/julia-raspbian/julia/src/gf.c:1933
#30 0x6612dac4 in julia_print_response_63515 () at REPL.jl:137
#31 0x6612db60 in jlcall_print_response_63514 ()

#32 0x76d58d10 in jl_call_fptr_internal (fptr=0x7effd604, fptr=0x7effd604, 
    nargs=7, args=0x7effd654, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:339
#33 jl_call_method_internal (nargs=7, args=0x7effd654, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:358
#34 jl_apply_generic (args=0x7effd654, nargs=7)
    at /home/pi/julia-raspbian/julia/src/gf.c:1933
#35 0x6612d888 in julia_print_response_63514 () at REPL.jl:129
#36 0x6612d8d0 in jlcall_print_response_63513 ()
#37 0x76d58d10 in jl_call_fptr_internal (fptr=0x7effd6bc, fptr=0x7effd6bc, 
    nargs=6, args=0x7effd77c, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:339
#38 jl_call_method_internal (nargs=6, args=0x7effd77c, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:358
#39 jl_apply_generic (args=0x7effd77c, nargs=6)
    at /home/pi/julia-raspbian/julia/src/gf.c:1933
#40 0x6612c95c in julia_do_respond_63504 () at REPL.jl:646
---Type <return> to continue, or q <return> to quit---
#41 0x6612ca90 in jlcall_do_respond_63503 ()
#42 0x76d58d10 in jl_call_fptr_internal (fptr=0x7effd9dc, fptr=0x7effd9dc, 
    nargs=4, args=0x7effda28, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:339
#43 jl_call_method_internal (nargs=4, args=0x7effda28, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:358
#44 jl_apply_generic (args=args@entry=0x7effda28, nargs=nargs@entry=4)
    at /home/pi/julia-raspbian/julia/src/gf.c:1933
#45 0x76d6e1e8 in do_call (args=args@entry=0x6e08eb10, nargs=nargs@entry=4, 
    s=s@entry=0x0) at /home/pi/julia-raspbian/julia/src/interpreter.c:75
#46 0x76d6d1dc in eval (e=e@entry=0x6e088f40, s=s@entry=0x0)
    at /home/pi/julia-raspbian/julia/src/interpreter.c:242
#47 0x76d6eda0 in eval_body (stmts=stmts@entry=0x6e08eb90, s=s@entry=0x0, 
    toplevel=1, start=0) at /home/pi/julia-raspbian/julia/src/interpreter.c:539
#48 0x76d6f100 in jl_toplevel_eval_body (stmts=0x6e08eb90)
    at /home/pi/julia-raspbian/julia/src/interpreter.c:511

#49 0x76d85b5c in jl_toplevel_eval_flex (e=e@entry=0x6e088f60, 
    expanded=expanded@entry=0, fast=1)
    at /home/pi/julia-raspbian/julia/src/toplevel.c:571
#50 0x76d85898 in jl_toplevel_eval (v=v@entry=0x6e088f60)
    at /home/pi/julia-raspbian/julia/src/toplevel.c:600

#51 0x76d67518 in jl_toplevel_eval_in (m=0x70060010, ex=0x6e088f60)
    at /home/pi/julia-raspbian/julia/src/builtins.c:496
---Type <return> to continue, or q <return> to quit---
#52 0x71a517a4 in julia_eval_17834 () at boot.jl:235
#53 0x71a517bc in jlcall_eval_17833 () from /usr/lib/julia/sys.so
#54 0x76d58d10 in jl_call_fptr_internal (fptr=0x7effe4e4, fptr=0x7effe4e4, 
    nargs=3, args=0x7effe5c0, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:339
#55 jl_call_method_internal (nargs=3, args=0x7effe5c0, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:358
#56 jl_apply_generic (args=0x7effe5c0, nargs=3)
    at /home/pi/julia-raspbian/julia/src/gf.c:1933
#57 0x71acaa20 in julia_run_interface_20015 () at LineEdit.jl:1583
#58 0x71acaa8c in jlcall_run_interface_20014 () from /usr/lib/julia/sys.so
#59 0x76d58d10 in jl_call_fptr_internal (fptr=0x7effe624, fptr=0x7effe624, 
    nargs=3, args=0x7effe6a4, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:339
#60 jl_call_method_internal (nargs=3, args=0x7effe6a4, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:358
#61 jl_apply_generic (args=0x7effe6a4, nargs=3)
    at /home/pi/julia-raspbian/julia/src/gf.c:1933
#62 0x71ce82ac in julia_run_frontend_31256 () at REPL.jl:945
#63 0x661282d4 in julia_run_repl_63478 () at REPL.jl:180
#64 0x66128304 in jlcall_run_repl_63477 ()
#65 0x76d58d10 in jl_call_fptr_internal (fptr=0x7effe74c, fptr=0x7effe74c, 
    nargs=3, args=0x7effe938, meth=<optimized out>)
---Type <return> to continue, or q <return> to quit---
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:339
#66 jl_call_method_internal (nargs=3, args=0x7effe938, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:358
#67 jl_apply_generic (args=0x7effe938, nargs=3)
    at /home/pi/julia-raspbian/julia/src/gf.c:1933
#68 0x71a95bd4 in julia__start_18766 () at client.jl:413
#69 0x71a95f18 in jlcall.start_18765 () from /usr/lib/julia/sys.so
#70 0x76d58d10 in jl_call_fptr_internal (fptr=0x7effeb74, fptr=0x7effeb74, 
    nargs=1, args=0x7effebd8, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:339
#71 jl_call_method_internal (nargs=1, args=0x7effebd8, meth=<optimized out>)
    at /home/pi/julia-raspbian/julia/src/julia_internal.h:358
#72 jl_apply_generic (args=args@entry=0x7effebd8, nargs=nargs@entry=1)
    at /home/pi/julia-raspbian/julia/src/gf.c:1933
#73 0x00011854 in jl_apply (nargs=1, args=0x7effebd8)
    at /home/pi/julia-raspbian/julia/ui/../src/julia.h:1424
#74 true_main (argc=<optimized out>, argv=<optimized out>)
    at /home/pi/julia-raspbian/julia/ui/repl.c:127
#75 0x000110b0 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/pi/julia-raspbian/julia/ui/repl.c:264
(gdb) 
(gdb) 
```

**Comment by ViralBShah** [comment]
Do the official binaries also do this?

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/14550 AFAICT.

**Comment by KristofferC** [comment]
That issue is closed?

**Comment by yuyichao** [comment]
Right. So this is already fixed.

**Comment by aviks** [comment]
The official binaries on Raspbian still has this issue, so something still needs doing. @ViralBShah can you verify which GCC we compiled that on? The issue @yuyichao linked seems to suggest that we need GCC 7.1.0.

**Comment by ViralBShah** [comment]
I mean does the issue  exist on official julialang binaries? The raspbian ones have a few more issues due to the insistence of using system llvm, and hence unless reproducible on official julialang binaries, the issues should not be filed.

**Comment by yuyichao** [comment]
The miscompilation comes from LLVM so it'll have this issue as long as you are using a llvm build that's compiled with affected gcc, doesn't really matter how julia itself is compiled.
