### ISSUE TITLE
Infinite loop in inference

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#25221]
With branch `nl/hash` (https://github.com/JuliaLang/julia/pull/16401), calling `x = Complex{Rational}(1//3 + 1//4*im); x^x` makes Julia enter an infinite loop. The top of the trace looks like this:

```
#2900 0x00007fffe617bd50 in japi1_abstract_call_method_1315 ()
    at inference.jl:2189
#2901 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2902 jl_call_method_internal (nargs=5, args=0x7fffffffb288, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2903 jl_apply_generic (args=0x7fffffffb288, nargs=5)
    at /home/milan/Dev/julia/src/gf.c:2011
#2904 0x00007fffe617af97 in japi1_abstract_call_gf_by_type_1071 ()
    at inference.jl:1955
#2905 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2906 jl_call_method_internal (nargs=5, args=0x7fffffffb460, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2907 jl_apply_generic (args=0x7fffffffb460, nargs=5)
    at /home/milan/Dev/julia/src/gf.c:2011
#2908 0x00007fffe616bca0 in japi1_abstract_call_1007 () at inference.jl:2640
#2909 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2910 jl_call_method_internal (nargs=6, args=0x7fffffffb670, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2911 jl_apply_generic (args=0x7fffffffb670, nargs=6)
    at /home/milan/Dev/julia/src/gf.c:2011
#2912 0x00007fffe6164d99 in japi1_abstract_eval_call_982 ()
    at inference.jl:2670
#2913 0x00007fffe6165325 in japi1_abstract_eval_977 () at inference.jl:2693
#2914 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2915 jl_call_method_internal (nargs=4, args=0x7fffffffb920, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2916 jl_apply_generic (args=0x7fffffffb920, nargs=4)
    at /home/milan/Dev/julia/src/gf.c:2011
#2917 0x00007fffe61662b2 in japi1_abstract_interpret_976 ()
    at inference.jl:2838
#2918 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2919 jl_call_method_internal (nargs=4, args=0x7fffffffba50, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2920 jl_apply_generic (args=0x7fffffffba50, nargs=4)
    at /home/milan/Dev/julia/src/gf.c:2011
#2921 0x00007fffe61330cd in julia_typeinf_work_43 () at inference.jl:3491
#2922 0x00007fffe6160d2f in japi1_typeinf_40 () at inference.jl:3622
#2923 0x00007fffe617d40f in japi1_typeinf_edge_1325 () at inference.jl:3353
#2924 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2925 jl_call_method_internal (nargs=5, args=0x7fffffffbdf0, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2926 jl_apply_generic (args=0x7fffffffbdf0, nargs=5)
    at /home/milan/Dev/julia/src/gf.c:2011
#2927 0x00007fffe617bd50 in japi1_abstract_call_method_1315 ()
    at inference.jl:2189
#2928 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2929 jl_call_method_internal (nargs=5, args=0x7fffffffbf88, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2930 jl_apply_generic (args=0x7fffffffbf88, nargs=5)
    at /home/milan/Dev/julia/src/gf.c:2011
#2931 0x00007fffe617af97 in japi1_abstract_call_gf_by_type_1071 ()
    at inference.jl:1955
#2932 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2933 jl_call_method_internal (nargs=5, args=0x7fffffffc160, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2934 jl_apply_generic (args=0x7fffffffc160, nargs=5)
    at /home/milan/Dev/julia/src/gf.c:2011
#2935 0x00007fffe616bca0 in japi1_abstract_call_1007 () at inference.jl:2640
#2936 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2937 jl_call_method_internal (nargs=6, args=0x7fffffffc370, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2938 jl_apply_generic (args=0x7fffffffc370, nargs=6)
    at /home/milan/Dev/julia/src/gf.c:2011
#2939 0x00007fffe6164d99 in japi1_abstract_eval_call_982 ()
    at inference.jl:2670
#2940 0x00007fffe6165325 in japi1_abstract_eval_977 () at inference.jl:2693
#2941 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2942 jl_call_method_internal (nargs=4, args=0x7fffffffc620, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2943 jl_apply_generic (args=0x7fffffffc620, nargs=4)
    at /home/milan/Dev/julia/src/gf.c:2011
#2944 0x00007fffe61662b2 in japi1_abstract_interpret_976 ()
    at inference.jl:2838
#2945 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2946 jl_call_method_internal (nargs=4, args=0x7fffffffc750, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2947 jl_apply_generic (args=0x7fffffffc750, nargs=4)
    at /home/milan/Dev/julia/src/gf.c:2011
#2948 0x00007fffe61330cd in julia_typeinf_work_43 () at inference.jl:3491
#2949 0x00007fffe6160d2f in japi1_typeinf_40 () at inference.jl:3622
#2950 0x00007fffe616d1d1 in typeinf_frame () at inference.jl:3312
#2951 julia_typeinf_code_1084 () at inference.jl:3405
#2952 0x00007fffe616d46b in jlcall_typeinf_code_1083 ()
   from /home/milan/Dev/julia/usr/lib/julia/sys.so
#2953 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2954 jl_call_method_internal (nargs=5, args=0x7fffffffcb48, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2955 jl_apply_generic (args=0x7fffffffcb48, nargs=5)
    at /home/milan/Dev/julia/src/gf.c:2011

#2956 0x00007fffe6161560 in julia_typeinf_ext_1 () at inference.jl:3447
#2957 0x00007fffe6161a50 in jlcall_typeinf_ext_0 ()
   from /home/milan/Dev/julia/usr/lib/julia/sys.so
#2958 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2959 jl_call_method_internal (nargs=3, args=0x7fffffffce80, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2960 jl_apply_generic (args=args@entry=0x7fffffffce80, nargs=nargs@entry=3)
    at /home/milan/Dev/julia/src/gf.c:2011
#2961 0x00007ffff772e7e7 in jl_apply (nargs=3, args=0x7fffffffce80)
    at /home/milan/Dev/julia/src/julia.h:1474
#2962 jl_apply_with_saved_exception_state (args=args@entry=0x7fffffffce80, 
    nargs=nargs@entry=3, drop_exceptions=drop_exceptions@entry=0)
    at /home/milan/Dev/julia/src/rtutils.c:257
#2963 0x00007ffff76bf3bb in jl_type_infer (pli=pli@entry=0x7fffffffcf90, 
    world=world@entry=25047, force=force@entry=0)
    at /home/milan/Dev/julia/src/gf.c:263
#2964 0x00007ffff76c1df7 in jl_compile_for_dispatch (
    pli=pli@entry=0x7fffffffcf90, world=world@entry=25047)
    at /home/milan/Dev/julia/src/gf.c:1705

#2965 0x00007ffff76c3538 in jl_compile_method_internal (
    meth=<optimized out>, fptr=<synthetic pointer>)
    at /home/milan/Dev/julia/src/julia_internal.h:348
#2966 jl_call_method_internal (nargs=3, args=0x7fffffffd000, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:395
#2967 jl_apply_generic (args=args@entry=0x7fffffffd000, 
    nargs=<optimized out>) at /home/milan/Dev/julia/src/gf.c:2011
#2968 0x00007ffff781865e in do_call (args=args@entry=0x7fffe3eec980, 
    nargs=nargs@entry=3, s=s@entry=0x7fffffffd480)
    at /home/milan/Dev/julia/src/interpreter.c:323
#2969 0x00007ffff78190be in eval_value (e=0x7fffe37be830, s=0x7fffffffd480)
    at /home/milan/Dev/julia/src/interpreter.c:395
#2970 0x00007ffff781a151 in eval_body (stmts=0x7fffe21ddc90, 
    s=0x7fffffffd480, start=<optimized out>, toplevel=1)
    at /home/milan/Dev/julia/src/interpreter.c:509
#2971 0x00007ffff781a74f in jl_interpret_toplevel_thunk_callback (
    s=0x7fffffffd480, vargs=0x7fffffffd4d0)
    at /home/milan/Dev/julia/src/interpreter.c:720
#2972 0x00007ffff76d863c in Lenter_interpreter_frame_start_val ()
   from /home/milan/Dev/julia/usr/bin/../lib/libjulia.so.0.7

#2973 0x00007ffff781b2dd in jl_interpret_toplevel_thunk (
    m=m@entry=0x7fffe6994910 <jl_system_image_data+10960>, 
    src=0x7fffe2f02250) at /home/milan/Dev/julia/src/interpreter.c:729
#2974 0x00007ffff76f8709 in jl_toplevel_eval_flex (
    m=m@entry=0x7fffe6994910 <jl_system_image_data+10960>, 
    e=e@entry=0x7fffe37bdfd0, fast=fast@entry=1, expanded=expanded@entry=0)
    at /home/milan/Dev/julia/src/toplevel.c:721
#2975 0x00007ffff76f8509 in jl_toplevel_eval (

    m=m@entry=0x7fffe6994910 <jl_system_image_data+10960>, 
    v=v@entry=0x7fffe37bdfd0) at /home/milan/Dev/julia/src/toplevel.c:734
#2976 0x00007ffff76d3938 in jl_toplevel_eval_in (
    m=0x7fffe6994910 <jl_system_image_data+10960>, ex=0x7fffe37bdfd0)
    at /home/milan/Dev/julia/src/builtins.c:626
#2977 0x00007fffe041a2d8 in eval () at boot.jl:289
#2978 japi1_eval_56311 () at repl/REPL.jl:3
#2979 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2980 jl_call_method_internal (nargs=3, args=0x7fffffffd7e8, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399

#2981 jl_apply_generic (args=0x7fffffffd7e8, nargs=3)
    at /home/milan/Dev/julia/src/gf.c:2011
#2982 0x00007fffe63b6534 in japi1_eval_user_input_12663 () at repl/REPL.jl:70
#2983 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2984 jl_call_method_internal (nargs=3, args=0x7fffffffda78, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2985 jl_apply_generic (args=0x7fffffffda78, nargs=3)
    at /home/milan/Dev/julia/src/gf.c:2011
#2986 0x00007fffe04148bc in macro expansion () at repl/REPL.jl:101
#2987 japi1_#1_56263 () at event.jl:92
#2988 0x00007ffff76c314a in jl_call_fptr_internal (fptr=<optimized out>, 
    fptr=<optimized out>, nargs=<optimized out>, args=<optimized out>, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:380
#2989 jl_call_method_internal (nargs=1, args=0x7fffe22f9558, 
    meth=<optimized out>) at /home/milan/Dev/julia/src/julia_internal.h:399
#2990 jl_apply_generic (args=args@entry=0x7fffe22f9558, nargs=nargs@entry=1)
    at /home/milan/Dev/julia/src/gf.c:2011
#2991 0x00007ffff76de5cb in jl_apply (nargs=1, args=0x7fffe22f9558)
    at /home/milan/Dev/julia/src/julia.h:1474
#2992 start_task () at /home/milan/Dev/julia/src/task.c:268
#2993 0x0000000000000000 in ?? ()
```

**Comment by vtjnash** [comment]
Is this still broken? The code above seems to work for me on master.

**Comment by nalimilan** [comment]
Indeed. See https://github.com/JuliaLang/julia/pull/25945.
