### ISSUE TITLE
Cannot install IJulia on Windows machine

### ISSUE THREAD

**Issue by ronyjj** [JuliaLang/julia#29090]
│ Downloading and Extracting Packages
│ Preparing transaction: ...working... done
│ Verifying transaction: ...working... done
│ Executing transaction: ...working... failed
│
│ ERROR conda.core.link:_execute(502): An error occurred while installing package 'defaults::ipykernel-4.9.0-py37_0'.
│ LinkError: post-link script failed for package defaults::ipykernel-4.9.0-py37_0
│ running your command again with `-v` will provide additional information
│ location of failed script: C:\Users\rjacob00c\.julia\packages\Conda\m7vem\deps\usr\Scripts\.ipykernel-post-link.bat
│ ==> script messages <==
│ <None>
│
│ Attempting to roll back.
│
│ Rolling back transaction: ...working... done
│
│ LinkError: post-link script failed for package defaults::ipykernel-4.9.0-py37_0
│ running your command again with `-v` will provide additional information
│ location of failed script: C:\Users\rjacob00c\.julia\packages\Conda\m7vem\deps\usr\Scripts\.ipykernel-post-link.bat
│ ==> script messages <==
│ <None>

**Comment by alkorang** [comment]
I installed Jupyter through Anaconda Prompt in start menu, and it works for Python.
But I got a different error when I build IJulia again.

```
(v1.0) pkg> build IJulia
  Building Conda ──→ `C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\build.log`
  Building ZMQ ────→ `C:\Users\alkorang\.julia\packages\ZMQ\ABGOx\deps\build.log`
  Building MbedTLS → `C:\Users\alkorang\.julia\packages\MbedTLS\Qo8TN\deps\build.log`
  Building IJulia ─→ `C:\Users\alkorang\.julia\packages\IJulia\k5o7j\deps\build.log`
┌ Error: Error building `IJulia`:
│ Solving environment: ...working... done
│
│ # All requested packages already installed.
│
│ Error executing Jupyter command 'kernelspec': [Errno 'jupyter-kernelspec' not found] 2
│ _cffi_ext.c
│ C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(213): fatal error C1083: ���� ����; �� �� ��4ϴ�. 'sys/un.h': No such file or directory
│ Exception in thread Thread-1:
│ Traceback (most recent call last):
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\threading.py", line 917, in _bootstrap_inner
│     self.run()
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\threading.py", line 865, in run
│     self._target(*self._args, **self._kwargs)
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\distutils\_msvccompiler.py", line 69, in _getall
│     all_packages.extend(_distutils_findvs.findall())
│ OSError: Error 8007007e
│
│ Traceback (most recent call last):
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\Scripts\jupyter-kernelspec-script.py", line 6, in <module>
│     from jupyter_client.kernelspecapp import KernelSpecApp
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
│     from .connect import *
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
│     import zmq
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\zmq\__init__.py", line 47, in <module>
│     from zmq import backend
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
│     reraise(*exc_info)
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
│     raise value
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
│     _ns = select_backend(first)
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
│     mod = __import__(name, fromlist=public_api)
│   File "C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
│     from . import (constants, error, message, context,
│ ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.
│ [ Info: Installing Jupyter via the Conda package.
│ [ Info: Running `conda install -y jupyter` in root environment
│ [ Info: Found Jupyter version 4.4.0: C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\Scripts\jupyter
│ [ Info: Installing Julia kernelspec julia-1.0
│ ERROR: LoadError: failed process: Process(`'C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\python.exe' 'C:\Users\alkorang\.julia\packages\Conda\m7vem\deps\usr\Scripts\jupyter-kernelspec-script.py' install --replace --user 'C:\Users\alkorang\AppData\Local\Temp\julia-1.0'`, ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
│  [2] pipeline_error at .\process.jl:695 [inlined]
│  [3] #run#505(::Bool, ::Function, ::Cmd) at .\process.jl:653
│  [4] run at .\process.jl:651 [inlined]
│  [5] #installkernel#4(::String, ::Function, ::String) at C:\Users\alkorang\.julia\packages\IJulia\k5o7j\deps\kspec.jl:85
│  [6] installkernel(::String) at C:\Users\alkorang\.julia\packages\IJulia\k5o7j\deps\kspec.jl:36
│  [7] top-level scope at logging.jl:310
│  [8] top-level scope at logging.jl:309
│  [9] top-level scope at C:\Users\alkorang\.julia\packages\IJulia\k5o7j\deps\build.jl:38
│  [10] include at .\boot.jl:317 [inlined]
│  [11] include_relative(::Module, ::String) at .\loading.jl:1038
│  [12] include(::Module, ::String) at .\sysimg.jl:29
│  [13] include(::String) at .\client.jl:388
│  [14] top-level scope at none:0
│ in expression starting at C:\Users\alkorang\.julia\packages\IJulia\k5o7j\deps\build.jl:9
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1068

(v1.0) pkg>
```

**Comment by KristofferC** [comment]
Please reopen on the IJulia repo (https://github.com/JuliaLang/IJulia.jl). Closing since this is not an issue with the language itself.
