### ISSUE TITLE
Can't build Julia from source on CentOS

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/julia#29328]
Make failed to build Julia from source on current master, even with the help of @vchuravy. 
```
[mprotter@cedar5 base]$ gcc --version
gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[mprotter@cedar5 base]$ uname -a
Linux cedar5.cedar.computecanada.ca 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 GNU/Linux
```

```
(gdb) r
Starting program: /home/mprotter/julia/usr/bin/julia -C native --output-ji /home/mprotter/julia/usr/lib/julia/corecompiler.ji.tmp --startup-file=no -g0 -O0 compiler/compiler.jl
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libthread_db.so.1".

warning: File "/cvmfs/soft.computecanada.ca/nix/store/5b0r0345k6rqdyil6ywwfa85jxj4r88p-gfortran-5.4.0-lib/lib/libstdc++.so.6.0.21-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /cvmfs/soft.computecanada.ca/nix/store/5b0r0345k6rqdyil6ywwfa85jxj4r88p-gfortran-5.4.0-lib/lib/libstdc++.so.6.0.21-gdb.py
line to your configuration file "/home/mprotter/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/mprotter/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[New Thread 0x7fffebe29700 (LWP 134957)]
julia: /home/mprotter/julia/usr/include/llvm/Support/Casting.h:255: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::GlobalVariable; Y = llvm::GlobalValue; typename llvm::cast_retty<X, Y*>::ret_type = llvm::GlobalVariable*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.

Thread 1 "julia" received signal SIGABRT, Aborted.
0x00007ffff6c92214 in raise () from /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6
(gdb)
(gdb) bt
#0  0x00007ffff6c92214 in raise () from /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6
#1  0x00007ffff6c9367a in abort () from /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6
#2  0x00007ffff6c8afe7 in __assert_fail_base () from /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6
#3  0x00007ffff6c8b092 in __assert_fail () from /cvmfs/soft.computecanada.ca/nix/store/63pk88rnmkzjblpxydvrmskkc8ci7cx6-glibc-2.24/lib/libc.so.6
#4  0x00007ffff7727688 in llvm::cast<llvm::GlobalVariable, llvm::GlobalValue> (Val=0x78d748) at /home/mprotter/julia/usr/include/llvm/Support/Casting.h:255
#5  emit_plt_thunk (runtime_lib=<optimized out>, symaddr=<optimized out>, llvmgv=0x787cc8, libptrgv=0x788ff8, f_name=<optimized out>, f_lib=<optimized out>, cc=<optimized out>,
    attrs=..., functype=0x764360, M=<optimized out>) at /home/mprotter/julia/src/ccall.cpp:281
#6  emit_plt (f_name=0x7fffe6bb8538 "jl_toplevel_eval_in", f_lib=<optimized out>, cc=<optimized out>, attrs=..., functype=0x764360, ctx=...) at /home/mprotter/julia/src/ccall.cpp:314
#7  function_sig_t::emit_a_ccall (this=this@entry=0x7fffffff87b0, ctx=..., symarg=..., nargt=<optimized out>, addressOf=..., argv=0x7fffffff8480, gc_uses=..., static_rt=true)
    at /home/mprotter/julia/src/ccall.cpp:1973
#8  0x00007ffff7733383 in emit_ccall (ctx=..., args=0x7fffe6e44288, args@entry=0x7fffe6e44290, nargs=<optimized out>) at /home/mprotter/julia/src/ccall.cpp:1797
#9  0x00007ffff772e739 in emit_expr (ctx=..., expr=expr@entry=0x7fffe6e3b7b0, ssaval=ssaval@entry=6) at /home/mprotter/julia/src/codegen.cpp:3882
#10 0x00007ffff7731135 in emit_ssaval_assign (ctx=..., idx=idx@entry=6, r=r@entry=0x7fffe6e3b7b0) at /home/mprotter/julia/src/codegen.cpp:3585
#11 0x00007ffff7736bac in emit_stmtpos (ssaval_result=6, expr=0x7fffe6e3b7b0, ctx=...) at /home/mprotter/julia/src/codegen.cpp:3771
#12 emit_function (lam=lam@entry=0x7fffe6e51890, src=<optimized out>, world=world@entry=1, declarations=<optimized out>, params=params@entry=0x7ffff7aa3040 <jl_default_cgparams>)
    at /home/mprotter/julia/src/codegen.cpp:6203
#13 0x00007ffff773c129 in jl_compile_linfo (pli=pli@entry=0x7fffffffa558, src=0x7fffe6e5e900, world=world@entry=1, params=0x7ffff7aa3040 <jl_default_cgparams>)
    at /home/mprotter/julia/src/codegen.cpp:1141
#14 0x00007ffff766667e in jl_compile_method_internal (world=<optimized out>, pli=0x7fffffffa558) at /home/mprotter/julia/src/gf.c:1808
#15 jl_fptr_trampoline (m=0x7fffe6e51890, args=0x7fffffffa608, nargs=1) at /home/mprotter/julia/src/gf.c:1842
#16 0x00007ffff76a62f2 in jl_toplevel_eval_flex (m=m@entry=0x7fffe6e4c010, e=<optimized out>, fast=fast@entry=1, expanded=expanded@entry=1) at /home/mprotter/julia/src/toplevel.c:812
#17 0x00007ffff767862e in jl_parse_eval_all (fname=fname@entry=0x7ffff77e9060 "boot.jl", content=content@entry=0x0, contentlen=contentlen@entry=0,
    inmodule=inmodule@entry=0x7fffe6e4c010) at /home/mprotter/julia/src/ast.c:881
#18 0x00007ffff76a7a73 in jl_load (module=0x7fffe6e4c010, fname=fname@entry=0x7ffff77e9060 "boot.jl") at /home/mprotter/julia/src/toplevel.c:852
#19 0x00007ffff7687a0e in _julia_init (rel=rel@entry=JL_IMAGE_JULIA_HOME) at /home/mprotter/julia/src/init.c:753
#20 0x00007ffff7687fbb in julia_init__threading (rel=JL_IMAGE_JULIA_HOME) at /home/mprotter/julia/src/task.c:305
#21 0x00000000004013e1 in main (argc=1, argv=0x7fffffffac68) at /home/mprotter/julia/ui/repl.c:227

(gdb) p llvmgv
$4 = <optimized out>
(gdb) p LM.m->dump()
; ModuleID = 'jl_toplevel_eval_in'
source_filename = "jl_toplevel_eval_in"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128-ni:10:11:12:13"
target triple = "x86_64-unknown-linux-gnu"

%jl_value_t = type opaque

@ccall_jl_toplevel_eval_in_14 = external global void ()*
@jl_RTLD_DEFAULT_handle = external constant i8*
@jlplt_jl_toplevel_eval_in_.1 = external global void ()*
@_j_str = external unnamed_addr constant [20 x i8]

define %jl_value_t addrspace(10)* @jlplt_jl_toplevel_eval_in_(%jl_value_t addrspace(10)*, %jl_value_t addrspace(10)*) {
top:
  %2 = load void ()*, void ()** @ccall_jl_toplevel_eval_in_14, align 8
  %3 = icmp ne void ()* %2, null
  br i1 %3, label %ccall, label %dlsym

dlsym:                                            ; preds = %top
  %4 = call void ()* @jl_load_and_lookup(i8* null, i8* getelementptr inbounds ([20 x i8], [20 x i8]* @_j_str, i32 0, i32 0), i8** @jl_RTLD_DEFAULT_handle)
  store atomic void ()* %4, void ()** @ccall_jl_toplevel_eval_in_14 release, align 8
  br label %ccall

ccall:                                            ; preds = %dlsym, %top
  %5 = phi void ()* [ %2, %top ], [ %4, %dlsym ]
  %6 = bitcast void ()* %5 to %jl_value_t addrspace(10)* (%jl_value_t addrspace(10)*, %jl_value_t addrspace(10)*)*
  %7 = bitcast %jl_value_t addrspace(10)* (%jl_value_t addrspace(10)*, %jl_value_t addrspace(10)*)* %6 to void ()*
  store atomic void ()* %7, void ()** @jlplt_jl_toplevel_eval_in_.1 release, align 8
  %8 = musttail call %jl_value_t addrspace(10)* %6(%jl_value_t addrspace(10)* %0, %jl_value_t addrspace(10)* %1)
  ret %jl_value_t addrspace(10)* %8
}

declare void ()* @jl_load_and_lookup(i8*, i8*, i8**)

!llvm.module.flags = !{!0, !1}

!0 = !{i32 2, !"Dwarf Version", i32 4}
!1 = !{i32 1, !"Debug Info Version", i32 3}
$5 = void
```

**Comment by MasonProtter** [comment]
This build was attempted with gcc 4, 6 and 7.
