### ISSUE TITLE
Julia inconsistent with stdin scripts

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#30039]
The behaviour when passing scripts via stdin in somewhat inconsistent and depends on how you do it exactly. Specifically:

When attaching a file or a heredoc to stdin, Julia does not terminate when it runs into an uncaught error:

```
$ echo 'println("A"); error("B"); println("C")' > test.jl; julia < test.jl; echo "-> $?"
A
ERROR: B
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at none:0
C
-> 0
```

```
$ julia <<EOF
println("A"); error("B"); println("C")
EOF  
A
ERROR: B
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at none:0
C
$ echo "-> $?"
-> 0
```

Whereas if you pipe, it does (but does not return an error code):

```
$ echo 'println("A"); error("B"); println("C")' | julia; echo "-> $?"
A
ERROR: B
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at none:0
-> 0
```

For completeness, this is what happens if you send the same thing in as a script:

```
$ echo 'println("A"); error("B"); println("C") ' > test.jl; julia test.jl; echo "-> $?"
A
ERROR: LoadError: B
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at none:0
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1044
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] exec_options(::Base.JLOptions) at ./client.jl:231
 [7] _start() at ./client.jl:425
in expression starting at /home/mortenpi/Julia/test/test.jl:1
-> 1
```

I would expect the behaviour to be consistent with how scripts are handled, i.e.:

* Always terminate when an error is thrown, but not caught.
* If there is an error, return an error code.

For comparison, e.g. Python behaves consistently:

```
$ echo 'print("A"); raise(Exception("B")); print("C")' | python3; echo "-> $?"
A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception: B
-> 1
$ echo 'print("A"); raise(Exception("B")); print("C")' > test.py; python3 < test.py; echo "-> $?"
A
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception: B
-> 1
```

My particular use case is that I would like to have the ability to pass heredocs to Julia in bash scripts, but have then behave like scripts (most importantly, that I could check the error code).

_Environment: Julia 1.0.2 generic binaries on Linux._

**Comment by mgkuhn** [comment]
Julia has two alternative ways of processing source code:
- interactively via the REPL (via base/client.jl:eval_user_input()):
    * the return value of each top-level expression is displayed (unless suppressed by a semicolon) and assigned to global variable `ans`
    * uncaught exceptions do not abort the julia process
- as a script (via include()):
    * return values are discarded (not displayed or assigned to `ans`)
    * uncaught exceptions abort the julia process

Looking at the implementation in [base/client.jl](https://github.com/JuliaLang/julia/blob/master/base/client.jl), if Julia reads statements from stdin, it currently does so via (a variant of) the REPL:

* the main Julia function `_start()` calls `exec_options()`
* `exec_options()` finds no filename argument in `ARGS` (which it would process via include()) and therefore calls `run_main_repl()`, passing `interactive=false` as stdin is not a TTY
* if `run_main_repl()` sees that is a file or pipe, it slurps all input into a string, parses it, and then hands each statement in the list it receives to `eval_user_input()` with show_value=true
* `eval_user_input()` catches any exception that happened during evaluation

I don't recall if Julia's behavior in this respect (when reading from a file or pipe) is documented in the manual currently, so I suspect that choice could be reviewed. I wouldn't call it “inconsistent”, it is just not consistent with the script mode you were probably expecting, but it is consistent with the REPL mode.

One could of course give `eval_user_input()` another parameter `catch_exceptions::Bool`, and set that to `false` if the REPL reads statements from a file or pipe, such that exceptions are then caught and displayed in `_start()` and not in `eval_user_input()`.

**Comment by laborg** [comment]
It appears that Julia now terminates, but the error code is still not returned.

**Comment by schlichtanders** [comment]
I am running into this when using Docker HEREDOC with julia

julia does not terminate or throw any error if an error occurs.
Docker HEREDOC are very nice, as you can use standard julia syntax without escaping.

Hence it would be great if this could be revived and made consistent.

**Comment by jkrumbiegel** [comment]
> I am running into this when using Docker HEREDOC with julia

Found this issue while trying to run julia commands in a Docker build script. Just leaving a solution I found here in which julia does not take the HEREDOC input as stdin but as a temporary file, therefore it works as expected for me, it doesn't execute and print line by line, and exit codes are propagated normally.

````
# syntax = docker/dockerfile:1.4

FROM julia:1.10

ENV NTHREADS=3

RUN <<EOF
#!/usr/bin/env -S julia --threads=${NTHREADS}
    if Threads.nthreads() == 3
        @warn("I don't like the number 3")
        exit(120)
    end
EOF
````

This gives the following output with `docker build  --progress=plain`:

```
#10 [2/2] RUN <<EOF (#!/usr/bin/env -S julia --threads=3...)
#10 sha256:ad16a35a5c90ab23fc35068f68528cbacd9fc6fd1be1badce7554dd93b6ca4b1
#10 0.668 ┌ Warning: I don't like the number 3
#10 0.668 └ @ Main /dev/pipes/EOF:3
#10 ERROR: executor failed running [/bin/sh -c /dev/pipes/EOF]: exit code: 120
```
