### ISSUE TITLE
segfault when loading big system image

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#31480]
I'm trying to load a statically compiled system image of many packages, which amounts to a 700mb sys.so. Removing random packages fixes the segfault - but not always. Since the removed packages work fine compiled individually, I started contemplated if the size of the system image itself could be the problem! 
A gdb stack trace seems to confirm that issue:
```
dt_compare (ap=0x1d712498ca89e380, 
    bp=0x7fffe1f9e2f8 <jl_system_image_data+342830264>)
    at /buildworker/worker/package_linux64/build/src/jltypes.c:625
#1  0x00007ffff6c89a70 in _quicksort (
    pbase=pbase@entry=0x7fffe1f9e2f8 <jl_system_image_data+342830264>, 
    total_elems=total_elems@entry=530344100283809828, size=size@entry=8, 
    cmp=cmp@entry=0x7ffff769c3b0 <dt_compare>, arg=0x0) at qsort.c:122
#2  0x00007ffff6c8b54c in __GI___qsort_r (
    b=0x7fffe1f9e2f8 <jl_system_image_data+342830264>, n=530344100283809828, 
    s=s@entry=8, cmp=cmp@entry=0x7ffff769c3b0 <dt_compare>, arg=arg@entry=0x0)
    at msort.c:216
#3  0x00007ffff6c8b6d8 in __GI_qsort (b=<optimized out>, n=<optimized out>, 
    s=s@entry=8, cmp=cmp@entry=0x7ffff769c3b0 <dt_compare>) at msort.c:308
#4  0x00007ffff769fee1 in jl_sort_types (types=<optimized out>, 
    length=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/jltypes.c:635
#5  0x00007ffff76dd3af in jl_restore_system_image_from_stream (
    f=f@entry=0x7fffffffc9e0)
    at /buildworker/worker/package_linux64/build/src/staticdata.c:1540
#6  0x00007ffff76e24d6 in jl_restore_system_image_data (
    buf=0x7fffcd8ab640 <jl_system_image_data> "$\300\230\020", 
    len=140736636752880)
    at /buildworker/worker/package_linux64/build/src/staticdata.c:1605
---Type <return> to continue, or q <return> to quit---
#7  0x00007ffff76e25b0 in jl_load_sysimg_so ()
    at /buildworker/worker/package_linux64/build/src/staticdata.c:200
#8  jl_restore_system_image (fname=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/staticdata.c:1578
#9  0x00007ffff76c89be in _julia_init (rel=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/init.c:782
#10 0x00007ffff76c90b5 in julia_init__threading (rel=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/task.c:222
#11 0x0000000000401518 in main (argc=<optimized out>, argv=<optimized out>)
    at /buildworker/worker/package_linux64/build/ui/repl.c:211
```
As one can see, there are some improbable lengths in there:
`len=140736636752880`
`total_elems=total_elems@entry=530344100283809828`

**Comment by JeffBezanson** [comment]
The wrong length might be a red herring, due to #31326.

**Comment by ViralBShah** [comment]
Please reopen if still an issue.
