### ISSUE TITLE
Segfault in PARTR code (rare)

### ISSUE THREAD

**Issue by RalphAS** [JuliaLang/julia#32520]
I have encountered rare segfaults while analyzing multithreaded code under recent nightlies
and local builds from master.
```
Julia Version 1.3.0-DEV.509
Commit 4d688468ba (2019-07-04 11:49 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 8
```

By "rare" I mean I need about 1000 repetitions of a code with a DAG depth of 10 and a couple thousand leaves to have a high probability of fault, so this is likely a subtle race condition.

So far, I have only observed this while profiling, which introduces extra non-deterministic  behavior.

Here is a typical backtrace:

```
signal (11): Segmentation fault
in expression starting at /tmp/partr/run1.jl:6
multiq_deletemin at /scratch/build/julia/src/partr.c:163
get_next_task at /scratch/build/julia/src/partr.c:403
jl_task_get_next at /scratch/build/julia/src/partr.c:423
poptaskref at ./task.jl:601
wait at ./task.jl:608
task_done_hook at ./task.jl:351
jl_fptr_args at /scratch/build/julia/src/gf.c:1809
_jl_invoke at /scratch/build/julia/src/gf.c:2043
jl_apply_generic at /scratch/build/julia/src/gf.c:2213
jl_apply at /scratch/build/julia/src/julia.h:1626
jl_finish_task at /scratch/build/julia/src/task.c:174
start_task at /scratch/build/julia/src/task.c:606
unknown function (ip: 0xffffffffffffffff)
Allocations: 1966193 (Pool: 1965836; Big: 357); GC: 10
Segmentation fault
```

Running a debug build under GDB:

```
Thread 5 "julia-debug" hit Breakpoint 1, sigdie_handler (sig=11, info=0x7fffcbbffbf0, context=0x7fffcbbffac0)
    at /scratch/build/julia/src/signals-unix.c:198
198	{
(gdb) up
#1  0x00007ffff753b97e in segv_handler (sig=11, info=0x7fffcbbffbf0, context=0x7fffcbbffac0) at /scratch/build/julia/src/signals-unix.c:274
274	        sigdie_handler(sig, info, context);
(gdb) up
#2  <signal handler called>
(gdb) up
#3  0x00007ffff7523ea8 in multiq_deletemin () at /scratch/build/julia/src/partr.c:163
163        if (jl_atomic_compare_exchange(&task->tid, -1, ptls->tid) != -1) {
(gdb) p heaps[rn1]
$3 = {lock = {owner = 140737010087680, count = 1}, tasks = 0x7ffff25f7010, ntasks = 0, prio = -1}
(gdb) p heaps[rn2]
$4 = {lock = {owner = 0, count = 0}, tasks = 0x7ffff1766010, ntasks = 0, prio = 32767}
(gdb) p heaps[rn1].tasks[0]
$5 = (jl_task_t *) 0x0
```

So the segfault is a null pointer reference (a nonexistent Task).

What follows should be regarded as suggestions intended to save the developers some time, rather than conclusive analysis. I do not understand the implementation well enough to propose a PR. Code references are to partr.c.

I suspect that the priority -1 (coming from an incompletely initialized Task, IIUC) is a strong clue. AFAICT this is set near the end of `multiq_deletemin`
```c
    if (heaps[rn1].ntasks > 0) {
        sift_down(&heaps[rn1], 0);
        prio1 = heaps[rn1].tasks[0]->prio;
    }
```
but there is no lock protecting the retrievals of `prio` in the earlier loop.
If I may go out on a limb, perhaps something like
```c
    if (task == NULL) { // we lost a race
      prio1 = INT16_MAX;
      jl_atomic_store(&heaps[rn1].prio, prio1);
      jl_mutex_unlock_nogc(&heaps[rn1].lock);
      goto retry;
    }
```
after `task = heaps[rn1].tasks[0];` (line 162) might be in order.

**Comment by JeffBezanson** [comment]
> but there is no lock protecting the retrievals of `prio` in the earlier loop.

IIUC, the check
```
        if (jl_mutex_trylock_nogc(&heaps[rn1].lock)) {
            if (prio1 == heaps[rn1].prio)
                break;
```
is supposed to correct for that. Maybe that should be an atomic load?
