### ISSUE TITLE
WITH_GC_DEBUG_ENV=1 segmentation faults in `gc_scrub_task`

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#33255]
With a Make.user off
```
JULIA_PRECOMPILE=0
USE_BINARYBUILDER_LLVM=0
# BINARYBUILDER_LLVM_ASSERTS=1
LLVM_ASSERTIONS=1
LLVM_DEBUG=1
FORCE_ASSERTIONS=1

# make the GC use regular malloc/frees
WITH_GC_DEBUG_ENV=1

# default to a debug build for better line numbers
override JULIA_BUILD_MODE=debug
```

I am reliably seeing a:

```
➜  julia-debug ./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0-DEV.119 (2019-09-13)
 _/ |\__'_|_|_|\__'_|  |  Commit 76cd21886f (0 days old master)
|__/                   |

julia: /home/vchuravy/src/julia/src/task.c:495: jl_sig_throw: Assertion `e && ptls->bt_size != 0' failed.

signal (6): Aborted
in expression starting at none:0
gsignal at /usr/lib/libc.so.6 (unknown line)
abort at /usr/lib/libc.so.6 (unknown line)
__assert_fail_base.cold at /usr/lib/libc.so.6 (unknown line)
__assert_fail at /usr/lib/libc.so.6 (unknown line)
jl_sig_throw at /home/vchuravy/src/julia/src/task.c:495
unknown function (ip: 0xffffffffffffffff)
Allocations: 1862287 (Pool: 0; Other: 1862287); GC: 1
Allocations: 1862287 (Pool: 0; Other: 1862287); GC: 1
fish: “./julia” terminated by signal SIGABRT (Abort)
```

Running with gdb or rr the segmentation fault occurs in:
```
Thread 1 "julia" received signal SIGSEGV, Segmentation fault.
0x00007ffff78c768c in gc_scrub_range (low=0x7fffd5609000 "", high=0x7fffd5a09000 "") at /home/vchuravy/src/julia/src/gc-debug.c:553
553	        char *p = *stack_p;
(gdb) bt
#0  0x00007ffff78c768c in gc_scrub_range (low=0x7fffd5609000 "", high=0x7fffd5a09000 "") at /home/vchuravy/src/julia/src/gc-debug.c:553
#1  0x00007ffff78c7969 in gc_scrub_task (ta=0x7fffe4e1e980) at /home/vchuravy/src/julia/src/gc-debug.c:602
#2  0x00007ffff78c79c0 in gc_scrub () at /home/vchuravy/src/julia/src/gc-debug.c:608
#3  0x00007ffff78c3fef in _jl_gc_collect (ptls=0x7ffff04574a0, full=0) at /home/vchuravy/src/julia/src/gc.c:2812
```

```
(gdb) p low
$2 = 0x7fffd5609000 ""
(gdb) p high
$3 = 0x7fffd5a09000 ""
(gdb) p stack_p
$4 = (char **) 0x7fffd5610ff8
(gdb) p *stack_p
$5 = 0x0
(gdb)
```

```
   0x00007ffff78c7680 <+180>:	jmpq   0x7ffff78c77f5 <gc_scrub_range+553>
   0x00007ffff78c7685 <+185>:	mov    -0x110(%rbp),%rax
=> 0x00007ffff78c768c <+192>:	mov    (%rax),%rax
```

```
(gdb) p/x $rax
$7 = 0x7fffd5610ff8
(gdb) p stack_p
$8 = (char **) 0x7fffd5610ff8
```

@yuyichao you touched the code last, any idea what might go wrong here?

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/issues/33045 again?

**Comment by yuyichao** [comment]
(Note that the abort you see without the debugger is not the segfault you see in the debugger)

**Comment by vchuravy** [comment]
Hm yeah, should have remembered that issue.
I thought I limited to that piece of the code since running with:
```
diff --git a/src/gc-debug.c b/src/gc-debug.c
index 30e63ca377..ade3a3c713 100644
--- a/src/gc-debug.c
+++ b/src/gc-debug.c
@@ -581,6 +581,7 @@ static void gc_scrub_task(jl_task_t *ta)
     jl_ptls_t ptls2 = NULL;
     if (tid != -1)
         ptls2 = jl_all_tls_states[tid];
+    return;

     char *low;
     char *high;
```

"fixed" it.
