### ISSUE TITLE
Hang when profiling loading `LLVM.jl`

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#38182]
On my system a `usr/bin/julia-debug -e "using Profile; @profile using LLVM"` causes Julia to hang.

Looking with GDB:

### Thread 1
```
0x00007f1c0ebec692 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007f1c0ebec692 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f1c0edfc8e2 in usr2_handler (sig=12, info=0x7f1c0a14bbf0, ctx=0x7f1c0a14bac0) at /home/vchuravy/src/julia/src/signals-unix.c:378
#2  <signal handler called>
#3  0x00007f1c0b921676 in bool llvm::DenseMapBase<llvm::DenseMap<llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::InfoRec, llvm::DenseMapInfo<llvm::BasicBlock*>, llvm::detail::DenseMapPair<llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::InfoRec> >, llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::InfoRec, llvm::DenseMapInfo<llvm::BasicBlock*>, llvm::detail::DenseMapPair<llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::InfoRec> >::LookupBucketFor<llvm::BasicBlock const*>(llvm::BasicBlock const* const&, llvm::detail::DenseMapPair<llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::InfoRec> const*&) const ()
   from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libLLVM-9jl.so
#4  0x00007f1c0b92563b in llvm::DenseMapBase<llvm::DenseMap<llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::InfoRec, llvm::DenseMapInfo<llvm::BasicBlock*>, llvm::detail::DenseMapPair<llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::InfoRec> >, llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::InfoRec, llvm::DenseMapInfo<llvm::BasicBlock*>, llvm::detail::DenseMapPair<llvm::BasicBlock*, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::InfoRec> >::FindAndConstruct(llvm::BasicBlock* const&) ()
   from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libLLVM-9jl.so
#5  0x00007f1c0b927bab in llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::runSemiNCA(llvm::DominatorTreeBase<llvm::BasicBlock, false>&, unsigned int) ()
   from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libLLVM-9jl.so
#6  0x00007f1c0b92814f in llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::CalculateFromScratch(llvm::DominatorTreeBase<llvm::BasicBlock, false>&, llvm::DomTreeBuilder::SemiNCAInfo<llvm::DominatorTreeBase<llvm::BasicBlock, false> >::BatchUpdateInfo*) () from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libLLVM-9jl.so
#7  0x00007f1c0b9f061a in (anonymous namespace)::Verifier::verify(llvm::Function const&) () from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libLLVM-9jl.so
#8  0x00007f1c0b9f0ce5 in (anonymous namespace)::VerifierLegacyPass::runOnFunction(llvm::Function&) () from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libLLVM-9jl.so
#9  0x00007f1c0b9743e8 in llvm::FPPassManager::runOnFunction(llvm::Function&) () from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libLLVM-9jl.so
#10 0x00007f1c0b974491 in llvm::FPPassManager::runOnModule(llvm::Module&) () from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libLLVM-9jl.so
#11 0x00007f1c0b9737d9 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libLLVM-9jl.so
#12 0x00007f1c0ee2c9b0 in JuliaOJIT::CompilerT::operator() (this=0x555559b77c78, M=...) at /home/vchuravy/src/julia/src/jitlayers.cpp:520
#13 0x00007f1c0ee3a9ad in llvm::orc::LegacyIRCompileLayer<llvm::orc::LegacyRTDyldObjectLinkingLayer, JuliaOJIT::CompilerT>::addModule (this=0x555559b77c70, K=13, M=std::unique_ptr<class llvm::Module> = {...})
    at /home/vchuravy/builds/julia-1.5/usr/include/llvm/ExecutionEngine/Orc/IRCompileLayer.h:93
#14 0x00007f1c0ee2dbba in JuliaOJIT::addModule (this=0x555559b76810, M=std::unique_ptr<class llvm::Module> = {...}) at /home/vchuravy/src/julia/src/jitlayers.cpp:648
#15 0x00007f1c0ee2ef74 in jl_add_to_ee (m=std::unique_ptr<class llvm::Module> = {...}) at /home/vchuravy/src/julia/src/jitlayers.cpp:893
#16 0x00007f1c0ee2f59e in jl_add_to_ee (M=std::unique_ptr<class llvm::Module> = {...}, NewExports=..., Queued=..., ToMerge=std::vector of length 1, capacity 1 = {...}, depth=1) at /home/vchuravy/src/julia/src/jitlayers.cpp:955
#17 0x00007f1c0ee2f801 in jl_add_to_ee (M=std::unique_ptr<class llvm::Module> = {...}, NewExports=...) at /home/vchuravy/src/julia/src/jitlayers.cpp:977
#18 0x00007f1c0ee2b396 in _jl_compile_codeinst (codeinst=0x7f1c04c664e0 <jl_system_image_data+47006496>, src=0x7f1bfd59aa10, world=27813) at /home/vchuravy/src/julia/src/jitlayers.cpp:126
#19 0x00007f1c0ee2bf59 in jl_generate_fptr (mi=0x7f1c023a45d0 <jl_system_image_data+4269072>, world=27813) at /home/vchuravy/src/julia/src/jitlayers.cpp:302
#20 0x00007f1c0ed85130 in jl_compile_method_internal (mi=0x7f1c023a45d0 <jl_system_image_data+4269072>, world=27813) at /home/vchuravy/src/julia/src/gf.c:1964
#21 0x00007f1c0ed85fc8 in _jl_invoke (F=0x7f1c023a41b0 <jl_system_image_data+4268016>, args=0x7ffe19e79858, nargs=3, mfunc=0x7f1c023a45d0 <jl_system_image_data+4269072>, world=27813) at /home/vchuravy/src/julia/src/gf.c:2224
#22 0x00007f1c0ed867c4 in jl_apply_generic (F=0x7f1c023a41b0 <jl_system_image_data+4268016>, args=0x7ffe19e79858, nargs=3) at /home/vchuravy/src/julia/src/gf.c:2398
#23 0x00007f1c01d02537 in jlcapi_dl_phdr_info_callback_28344 () from /home/vchuravy/builds/julia-1.5/usr/lib/julia/sys-debug.so
#24 0x00007f1c0eb4df95 in dl_iterate_phdr () from /usr/lib/libc.so.6
#25 0x00007f1c01d022f3 in julia_dllist_28343 () at /home/vchuravy/builds/julia-1.5/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:297
#26 0x00007f1be4b56e63 in julia___init___11 () at /home/vchuravy/.julia/packages/LLVM/KITdB/src/LLVM.jl:60
#27 0x00007f1be4b580ed in jfptr___init___12 ()
#28 0x00007f1c0ed8600e in _jl_invoke (F=0x7f1bfdcc88e0, args=0x7ffe19e79e80, nargs=0, mfunc=0x7f1bff5a4190, world=27813) at /home/vchuravy/src/julia/src/gf.c:2231
#29 0x00007f1c0ed867c4 in jl_apply_generic (F=0x7f1bfdcc88e0, args=0x7ffe19e79e80, nargs=0) at /home/vchuravy/src/julia/src/gf.c:2398
#30 0x00007f1c0edc8ade in jl_apply (args=0x7ffe19e79e78, nargs=1) at /home/vchuravy/src/julia/src/julia.h:1690
#31 0x00007f1c0edc9166 in jl_module_run_initializer (m=0x7f1bff10c760) at /home/vchuravy/src/julia/src/toplevel.c:74
```

### Thread 2
```
(gdb) t 2
[Switching to thread 2 (Thread 0x7f1c0a9e9640 (LWP 77520))]
#0  0x00007f1c0ebefdb0 in __lll_lock_wait () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007f1c0ebefdb0 in __lll_lock_wait () from /usr/lib/libpthread.so.0
#1  0x00007f1c0ebe87d1 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#2  0x00007f1c0eb4de51 in dl_iterate_phdr () from /usr/lib/libc.so.6
#3  0x00007f1c0e7e9d39 in _ULx86_64_dwarf_find_proc_info () from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libunwind.so.8
#4  0x00007f1c0e7e72d6 in fetch_proc_info () from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libunwind.so.8
#5  0x00007f1c0e7e86cf in find_reg_state () from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libunwind.so.8
#6  0x00007f1c0e7e894d in _ULx86_64_dwarf_step () from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libunwind.so.8
#7  0x00007f1c0e7e1c05 in _ULx86_64_step () from /home/vchuravy/builds/julia-1.5/usr/bin/../lib/libunwind.so.8
#8  0x00007f1c0ede53b1 in jl_unw_step (cursor=0x7f1c0a9e0d30, ip=0x7f1c0a9e0bb0, sp=0x7f1c0a9e0bb8, lockless=1) at /home/vchuravy/src/julia/src/stackwalk.c:569
#9  0x00007f1c0ede4530 in jl_unw_stepn (cursor=0x7f1c0a9e0d30, bt_data=0x7f1bfb2dc930, bt_size=0x7f1c0a9e0d28, sp=0x0, maxsize=943899, skip=0, ppgcstack=0x7f1c0a9e0d00, from_signal_handler=1, lockless=1)
    at /home/vchuravy/src/julia/src/stackwalk.c:99
#10 0x00007f1c0ede47de in rec_backtrace_ctx (bt_data=0x7f1bfb2dc930, maxsize=943899, context=0x7f1c0a14bac0, pgcstack=0x0, lockless=1) at /home/vchuravy/src/julia/src/stackwalk.c:188
#11 0x00007f1c0edfd14f in signal_listener (arg=0x0) at /home/vchuravy/src/julia/src/signals-unix.c:695
#12 0x00007f1c0ebe63e9 in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007f1c0eb14293 in clone () from /usr/lib/libc.so.6
```

@vtjnash diagnosed this on Slack as:
> libunwind prohibits itself from taking locks, so that’s a bug in libunwind

cc: @jpsamaroo @maleadt

**Comment by giordano** [comment]
Doesn't seem to be an issue anymore:
```console
$ time usr/bin/julia-debug -e "using Profile; @profile using LLVM"; echo $?
┌ Error: LLVM extensions library unavailable for your platform:
│   x86_64-linux-gnu-libgfortran5-cxx11-libstdcxx30-llvm_version+18-julia_version+1.12.0
│ LLVM.jl will not be functional.
│
│ If you are using a custom version of LLVM, try building a
│ custom version of LLVMExtra_jll using `deps/build_local.jl`
└ @ LLVM ~/.julia/packages/LLVM/UqMfW/src/LLVM.jl:108

real    0m3.912s
user    0m4.766s
sys     0m0.345s
0
$ usr/bin/julia-debug -e 'using InteractiveUtils; versioninfo()'
Julia Version 1.12.0-DEV.1054
Commit 5230d27de9* (2024-08-16 07:33 UTC)
Build Info:
  DEBUG build
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × AMD Ryzen 9 3950X 16-Core Processor
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 32 virtual cores)
```
(there's a logging message of error level because I'm using nightly, but LLVM can be loaded regularly and the process exits with code 0)
