### ISSUE TITLE
`jl_sigint_safepoint()` causes segfault if run too early

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#39006]
I'm not entirely sure what the purpose of `jl_sigint_safepoint()` segfaulting is, but if run too early (because, for instance, `jl_init()` fails and tries to print something out to `stdout`, which in turn calls `jl_uv_puts()` which calls `JL_SIGATOMIC_END()`) it can cause an actual segfault.  I think we may need to either prevent that segfault from being raised if we are not initialized enough to handle it, or we need to avoid calling things like `jl_uv_puts()` until we're more initialized.

**Comment by staticfloat** [comment]
I found this while debugging https://github.com/JuliaLang/julia/pull/39009

To reproduce, the following patch will segfault on bootstrap:

```diff
diff --git a/src/init.c b/src/init.c
index 45c293c887..5aa25425e7 100644
--- a/src/init.c
+++ b/src/init.c
@@ -660,6 +660,7 @@ void _julia_init(JL_IMAGE_SEARCH rel)
     jl_init_stack_limits(1, &stack_lo, &stack_hi);
 
     // Load libjulia-internal (which contains this function), and libjulia, explicitly.
+    jl_uv_puts(JL_STDERR, "test", 4);
     jl_libjulia_internal_handle = jl_load_dynamic_library(NULL, JL_RTLD_DEFAULT, 1);
     jl_libjulia_handle = jl_load_dynamic_library(JL_LIBJULIA_SONAME, JL_RTLD_DEFAULT, 1);
 #ifdef _OS_WINDOWS_
```

The backtrace is, accordingly:
```
(gdb) r
Starting program: /home/sabae/src/julia/usr/bin/julia -g1 -O0 -C native --output-ji /home/sabae/src/julia/usr/lib/julia/sys.ji.tmp --startup-file=no --warn-overwrite=yes --sysimage /home/sabae/src/julia/usr/lib/julia/corecompiler.ji sysimg.jl ./
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff2e17700 (LWP 1955135)]
test
Thread 1 "julia" received signal SIGSEGV, Segmentation fault.
0x00007ffff765ae74 in jl_uv_puts (stream=<optimized out>, str=0x7ffff776061e "test", n=4) at /home/sabae/src/julia/src/jl_uv.c:541
541             JL_SIGATOMIC_END();
(gdb) bt
#0  0x00007ffff765ae74 in jl_uv_puts (stream=<optimized out>, str=0x7ffff776061e "test", n=4) at /home/sabae/src/julia/src/jl_uv.c:541
#1  0x00007ffff763d6d4 in _julia_init (rel=JL_IMAGE_CWD) at /home/sabae/src/julia/src/init.c:663
#2  0x00007ffff763e619 in julia_init__threading (rel=<optimized out>) at /home/sabae/src/julia/src/task.c:317
#3  0x00007ffff767b208 in repl_entrypoint (argc=<optimized out>, argv=<optimized out>) at /home/sabae/src/julia/src/jlapi.c:693
#4  0x000055555555508d in main (argc=<optimized out>, argv=<optimized out>) at /home/sabae/src/julia/cli/loader_exe.c:51
```
