### ISSUE TITLE
Segfault loading GLMakie

### ISSUE THREAD

**Issue by chriselrod** [JuliaLang/julia#40406]
Not sure of the cause -- I could upload an rr trace. Not that familiar with gdb, but could poke around later myself to try and see if I can figure something out.
```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(makie) pkg> up
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
  No Changes to `~/Documents/progwork/julia/env/makie/Project.toml`
    Updating `~/Documents/progwork/julia/env/makie/Manifest.toml`
  [3f19e933] + p7zip_jll
Precompiling project...
  Progress [========================================>]  134/134
  ✗ GLMakie
  ✗ Makie
132 dependencies successfully precompiled in 78 seconds
2 dependencies errored

julia> using Makie
[ Info: Precompiling Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a]

signal (11): Segmentation fault
in expression starting at /home/chriselrod/.julia/packages/GLMakie/AHGzN/src/gl_backend.jl:1
unknown function (ip: (nil))
unknown function (ip: 0x7fae94ff5f6d)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
jl_module_run_initializer at /buildworker/worker/package_linux64/build/src/toplevel.c:72
jl_init_restored_modules at /buildworker/worker/package_linux64/build/src/dump.c:2109
_include_from_serialized at ./loading.jl:674
_require_search_from_serialized at ./loading.jl:760
_require at ./loading.jl:998
require at ./loading.jl:914
require at ./loading.jl:901
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
call_require at /buildworker/worker/package_linux64/build/src/toplevel.c:421 [inlined]
eval_import_path at /buildworker/worker/package_linux64/build/src/toplevel.c:458
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:684
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:528
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:489
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:669
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
include_string at ./loading.jl:1094
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
_include at ./loading.jl:1148
include at ./Base.jl:386
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
jl_f__call_latest at /buildworker/worker/package_linux64/build/src/builtins.c:714
include at /home/chriselrod/.julia/packages/GLMakie/AHGzN/src/GLMakie.jl:1
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:155 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:561
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:669
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_eval_module_expr at /buildworker/worker/package_linux64/build/src/toplevel.c:195 [inlined]
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:668
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
include_string at ./loading.jl:1094
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
_include at ./loading.jl:1148
include at ./Base.jl:386 [inlined]
include_package_for_output at ./loading.jl:1213
jfptr_include_package_for_output_47362.clone_1 at /home/chriselrod/Downloads/julia-1.6.0/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:155 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:561
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:669
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
eval at ./client.jl:446
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:155 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:561
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:669
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
exec_options at ./client.jl:261
_start at ./client.jl:485
jfptr__start_41020.clone_1 at /home/chriselrod/Downloads/julia-1.6.0/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
true_main at /buildworker/worker/package_linux64/build/src/jlapi.c:560
repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:702
main at /buildworker/worker/package_linux64/build/cli/loader_exe.c:51
__libc_start_main at /usr/lib64/haswell/libc.so.6 (unknown line)
_start at /home/chriselrod/Downloads/julia-1.6.0/bin/julia (unknown line)
Allocations: 10121655 (Pool: 10119204; Big: 2451); GC: 5
ERROR: LoadError: Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to /home/chriselrod/.julia/compiled/v1.6/GLMakie/jl_zvKkPF.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY)
    @ Base ./loading.jl:1360
  [3] compilecache(pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1306
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1021
  [5] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:914
  [6] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:901
  [7] include
    @ ./Base.jl:386 [inlined]
  [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1213
  [9] top-level scope
    @ none:1
 [10] eval
    @ ./boot.jl:360 [inlined]
 [11] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [12] top-level scope
    @ none:1
in expression starting at /home/chriselrod/.julia/packages/Makie/iTycG/src/Makie.jl:1
ERROR: Failed to precompile Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a] to /home/chriselrod/.julia/compiled/v1.6/Makie/jl_QilWwP.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY)
   @ Base ./loading.jl:1360
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1306
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1021
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:914
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:901

(makie) pkg> st
      Status `~/Documents/progwork/julia/env/makie/Project.toml`
  [ee78f7c6] Makie v0.12.0

julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
```
The segfault doesn't kill the main Julia process, so it's not as bad as it looks.

**Comment by vchuravy** [comment]
Can you get a backtrace out of GDB? Maybe necessitates rebuilding julia with `LLVM_DEBUG=2`

**Comment by vchuravy** [comment]
Also what is your GL stack? Which GPU are you using, etc...

**Comment by chriselrod** [comment]
```julia
Starting program: /home/chriselrod/Documents/languages/juliarelease/usr/bin/julia --project=\~/Documents/progwork/julia/env/makie/ -e using\ GLFW
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[New Thread 0x7ffff26af700 (LWP 119154)]
[New Thread 0x7fffe1ce0700 (LWP 119163)]
[New Thread 0x7fffd94df700 (LWP 119164)]
[New Thread 0x7fffe0841700 (LWP 119165)]
[New Thread 0x7fffdb361700 (LWP 119166)]
[New Thread 0x7fffd9ec2700 (LWP 119167)]
[New Thread 0x7fffc3fff700 (LWP 119168)]
[New Thread 0x7fffcb3fe700 (LWP 119169)]
[New Thread 0x7fffc9ffc700 (LWP 119170)]
[New Thread 0x7fffc8bfa700 (LWP 119171)]
[New Thread 0x7fffc2bfd700 (LWP 119172)]
[New Thread 0x7fffc17fb700 (LWP 119173)]
[New Thread 0x7fffa3fff700 (LWP 119174)]
[New Thread 0x7fffab3fe700 (LWP 119175)]
[New Thread 0x7fffa9ffc700 (LWP 119176)]
[New Thread 0x7fffa8bfa700 (LWP 119177)]
[New Thread 0x7fffa2bfd700 (LWP 119178)]
[New Thread 0x7fffa17fb700 (LWP 119179)]
[New Thread 0x7fff8bfff700 (LWP 119180)]
[New Thread 0x7fff8abfd700 (LWP 119181)]
[New Thread 0x7fff897fb700 (LWP 119182)]
[New Thread 0x7fff77fff700 (LWP 119183)]
[New Thread 0x7fff6ffff700 (LWP 119184)]
[New Thread 0x7fff75ffc700 (LWP 119185)]
[New Thread 0x7fff74bfa700 (LWP 119186)]
[New Thread 0x7fff6ebfd700 (LWP 119187)]
[New Thread 0x7fff6d7fb700 (LWP 119188)]
[New Thread 0x7fff57fff700 (LWP 119189)]
[New Thread 0x7fff4ffff700 (LWP 119190)]
[New Thread 0x7fff55ffc700 (LWP 119191)]
[New Thread 0x7fff54bfa700 (LWP 119192)]
[New Thread 0x7fff4ebfd700 (LWP 119193)]
[New Thread 0x7fff4d7fb700 (LWP 119194)]
[New Thread 0x7fff37fff700 (LWP 119195)]
[New Thread 0x7fff2ffff700 (LWP 119196)]
[New Thread 0x7fff35ffc700 (LWP 119197)]
[New Thread 0x7fff2d806700 (LWP 119218)]
[New Thread 0x7fff2d005700 (LWP 119219)]
[New Thread 0x7fff2c804700 (LWP 119220)]
[New Thread 0x7fff27fff700 (LWP 119221)]
[New Thread 0x7fff277fe700 (LWP 119222)]
[New Thread 0x7fff26ffd700 (LWP 119223)]
[New Thread 0x7fff267fc700 (LWP 119224)]

Thread 1 "julia" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffecf7daab1 in _glfwPlatformInit () from /home/chriselrod/.julia/artifacts/ded9d2caacc9a40cabeae1e02a77a310247f81b8/lib/libglfw.so
#2  0x00007ffecf7d2fc2 in glfwInit () from /home/chriselrod/.julia/artifacts/ded9d2caacc9a40cabeae1e02a77a310247f81b8/lib/libglfw.so
#3  0x00007fff74076a81 in ?? ()
#4  0x0000555555ab4fd8 in ?? ()
#5  0x0000555555ab4fe8 in ?? ()
#6  0x00005555561e9e90 in ?? ()
#7  0x0000000100000000 in ?? ()
#8  0x00007fff00000040 in ?? ()
#9  0x0000000000000000 in ?? ()
```
With
```julia
USE_BINARYBUILDER_LLVM=0
LLVM_DEBUG=2
```
in my Make.user, so the fact that the backtrace shows only stripped symbols makes it look like I was wrong to think it was an LLVM symbol conflict like it once was (i.e., that the problem is somewhere in glfw)?



Here is part of the output of `glxinfo`:
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: Radeon RX Vega (VEGA10, DRM 3.40.0, 5.10.19-1032.native, LLVM 10.0.1) (0x687f)
    Version: 21.0.1
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 7875 MB, largest block: 7875 MB
    VBO free aux. memory - total: 8096 MB, largest block: 8096 MB
    Texture free memory - total: 7875 MB, largest block: 7875 MB
    Texture free aux. memory - total: 8096 MB, largest block: 8096 MB
    Renderbuffer free memory - total: 7875 MB, largest block: 7875 MB
    Renderbuffer free aux. memory - total: 8096 MB, largest block: 8096 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 16368 MB
    Currently available dedicated video memory: 7875 MB
OpenGL vendor string: AMD
OpenGL renderer string: Radeon RX Vega (VEGA10, DRM 3.40.0, 5.10.19-1032.native, LLVM 10.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.0.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
```
GPU is a Vega 64, and I'm on Mesa 21.0.1.

**Comment by ViralBShah** [comment]
Let's reopen if still an issue.
