### ISSUE TITLE
Conda installation error

### ISSUE THREAD

**Issue by renatobellotti** [JuliaLang/julia#42448]
I get the following error message when I try to install Julia with anaconda:

```
$ conda install --force-reinstall julia
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/renato/.conda/envs/julia_env

  added / updated specs:
    - julia



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: \ ERROR: KeyError: key "JULIA_PKGDIR" not found
Stacktrace:
 [1] (::Base.var"#509#510")(k::String)
   @ Base ./env.jl:79
 [2] access_env
   @ ./env.jl:43 [inlined]
 [3] getindex(#unused#::Base.EnvDict, k::String)
   @ Base ./env.jl:79
 [4] top-level scope
   @ none:1

WARNING conda.core.link:run_script(1202): pre-unlink script failed for package conda-forge/linux-64::julia-1.6.3-h2a39549_1
consider notifying the package maintainer
\ 
done
```

The installation seems to be fine at first and I can run the interpreter fine, but then I get errors when trying to run it on Jupyter:

```
[E 2021-10-01 09:45:28.714 ServerApp] Uncaught exception GET /api/kernels?1633074328618 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels?1633074328618', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/renato/.local/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/home/renato/.local/lib/python3.9/site-packages/jupyter_server/services/kernels/handlers.py", line 35, in get
        kernels = await ensure_async(km.list_kernels())
      File "/home/renato/.local/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 459, in list_kernels
        model = self.kernel_model(kernel_id)
      File "/home/renato/.local/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 447, in kernel_model
        "last_activity": isoformat(kernel.last_activity),
    AttributeError: 'AsyncIOLoopKernelManager' object has no attribute 'last_activity'
[W 2021-10-01 09:45:28.718 ServerApp] Unhandled error
[E 2021-10-01 09:45:28.719 ServerApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0",
      "Accept": "*/*",
      "Accept-Language": "en-GB,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab/workspaces/auto-F/tree/01/solution/solution_01.ipynb",
      "Authorization": "token 338b35546f57ecfaaab93bb120a5dcb3e860ea7e725be26d",
      "X-Xsrftoken": "2|a29708ce|bbb852dafd9b1f4002d4156ed0cb9710|1632214760",
      "Content-Type": "application/json",
      "Dnt": "1",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1633074328|23:username-localhost-8888|44:MDgwODc2NjFjODM1NDA2MTk4MGVkMzQxYzBjMjRmYWU=|026b0d10282215c0d2a329a53a738b36e6d918d445a89a1e8d39a3d063acea23\"; _xsrf=2|a29708ce|bbb852dafd9b1f4002d4156ed0cb9710|1632214760",
      "Sec-Fetch-Dest": "empty",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Gpc": "1",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 2021-10-01 09:45:28.719 ServerApp] 500 GET /api/kernels?1633074328618 (127.0.0.1) 13.80ms referer=http://localhost:8888/lab/workspaces/auto-F/tree/01/solution/solution_01.ipynb
[I 2021-10-01 09:45:28.721 ServerApp] Kernel started: 169292bd-6e08-45d6-a26a-cc9345a9b7fb
[E 2021-10-01 09:45:33.272 ServerApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/home/renato/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
        callback(*args, **kwargs)
      File "/home/renato/.local/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 494, in record_activity
        msg = session.deserialize(fed_msg_list)
      File "/home/renato/.local/lib/python3.9/site-packages/jupyter_client/session.py", line 1042, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: b'2e8621b4e2161447abbe29a70c1ea92fef2343224cf83ae2874309ad86dee881eb7294906bc696f074876e8813276d390b15ac77a2fceccdaab2851a4f2f33f5'
[E 2021-10-01 09:45:33.272 ServerApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/home/renato/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
        self._handle_recv()
      File "/home/renato/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
        self._run_callback(callback, msg)
      File "/home/renato/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
        callback(*args, **kwargs)
      File "/home/renato/.local/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 494, in record_activity
        msg = session.deserialize(fed_msg_list)
      File "/home/renato/.local/lib/python3.9/site-packages/jupyter_client/session.py", line 1042, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: b'2e8621b4e2161447abbe29a70c1ea92fef2343224cf83ae2874309ad86dee881eb7294906bc696f074876e8813276d390b15ac77a2fceccdaab2851a4f2f33f5'
Exception in callback BaseAsyncIOLoop._handle_events(24, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(24, 1)>
Traceback (most recent call last):
  File "/home/renato/.conda/envs/julia_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/renato/.local/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/renato/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
    self._handle_recv()
  File "/home/renato/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/renato/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/home/renato/.local/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 494, in record_activity
    msg = session.deserialize(fed_msg_list)
  File "/home/renato/.local/lib/python3.9/site-packages/jupyter_client/session.py", line 1042, in deserialize
    raise ValueError("Invalid Signature: %r" % signature)
ValueError: Invalid Signature: b'2e8621b4e2161447abbe29a70c1ea92fef2343224cf83ae2874309ad86dee881eb7294906bc696f074876e8813276d390b15ac77a2fceccdaab2851a4f2f33f5'
Starting kernel event loops.
```
I have already recreated the entire conda env, deleted the cache, and reinstalled ``Julia`` and ``IJulia``, but I still cannot get Jupyter running. Any help is highly appreciated!

**Comment by DilumAluthge** [comment]
Conda is not an official supported installation method for Julia.

I would recommend that you download the official binaries: https://julialang.org/downloads/

If you do want to use Conda to install Julia, you will need to reach out to the people that maintain the Conda recipe for Julia.

**Comment by renatobellotti** [comment]
I was not aware of this. I tried now with the Fedora package and it works. Thanks for your help!

**Comment by aanish-pradhan** [comment]
> I was not aware of this. I tried now with the Fedora package and it works. Thanks for your help!

Hi! I've been trying to install Julia via Conda and interface it to Jupyter Notebooks with the IJulia kernel to no avail. Surprisingly, it works outside of a Conda environment.

Just two questions:

1. Any updates from an official Julia or Conda source about this issue and whether it is fixed?
2. What do you mean by "Fedora" package? Do you mean the Julia binary through the Fedora package manager?

**Comment by renatobellotti** [comment]
>     2. What do you mean by "Fedora" package? Do you mean the Julia binary through the Fedora package manager?
Yes
