### ISSUE TITLE
Heisenbug in "test guarded Random.seed!"

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#42752]
Just as a record, I saw:

```
Error in testset Test:
Test Failed at /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.8/Test/test/runtests.jl:777
  Expression: orig == Random.default_rng()
   Evaluated: Xoshiro(0x947b9af2ba269897, 0x95ae8d9a31382b32, 0x8a532dc2baa61f2e, 0x7213512241a4dfbd) == TaskLocalRNG()
Error in testset Test:
Test Failed at /buildworker/worker/tester_linuxaarch64/build/share/julia/stdlib/v1.8/Test/test/runtests.jl:778
  Expression: rand(orig) == rand()
   Evaluated: 0.6209946085911393 == 0.7846500004305739
```

https://build.julialang.org/#/builders/7/builds/4863/steps/5/logs/stdio

in #42725. It vanished after re-running the test by merging `master` even though there doesn't seem a change that could fix the result https://github.com/JuliaLang/julia/compare/a4903fd0e7882532b3329ab47888c3c051f868cc...76c243141a611da572bda3332f836b898998225f.

**Comment by tkf** [comment]
Is it architecture-specific?

**Comment by Seelengrab** [comment]
Is this expected/related behavior?

```
[sukera@tempman ~]$ julia -q -t1
julia> t = current_task()
Task (runnable) @0x00007f6723fdc010

julia> state = (t.rngState0, t.rngState1, t.rngState2, t.rngState3)
(0xf6e7025b1a108853, 0x1949f9d36755c8cf, 0xdc13b6c30461a2b5, 0xb199766836484420)

julia> using Random

julia> copy(Random.default_rng()) # yep, same state as the rng in our task
Xoshiro(0xf6e7025b1a108853, 0x1949f9d36755c8cf, 0xdc13b6c30461a2b5, 0xb199766836484420)

julia> Random.default_rng()
TaskLocalRNG()

julia> function Base.show(io::IO, ::MIME"text/plain", x::Random.TaskLocalRNG)
           t = current_task()
           write(io, "TaskLocalRNG(")
           show(io, MIME"text/plain"(), t.rngState0)
           write(io, ',')
           show(io, MIME"text/plain"(), t.rngState1)
           write(io, ',')
           show(io, MIME"text/plain"(), t.rngState2)
           write(io, ',')
           show(io, MIME"text/plain"(), t.rngState3)
           print(io, ')')
       end

julia> state1 = (t.rngState0, t.rngState1, t.rngState2, t.rngState3) # ok, our state didn't change..
(0xf6e7025b1a108853, 0x1949f9d36755c8cf, 0xdc13b6c30461a2b5, 0xb199766836484420)

julia> t = current_task()  # still the same task
Task (runnable) @0x00007f6723fdc010

julia> state1 = (t.rngState0, t.rngState1, t.rngState2, t.rngState3)  # still the same state
(0xf6e7025b1a108853, 0x1949f9d36755c8cf, 0xdc13b6c30461a2b5, 0xb199766836484420)

julia> copy(Random.default_rng()) # should just copy rng of current task, so far so good
Xoshiro(0xf6e7025b1a108853, 0x1949f9d36755c8cf, 0xdc13b6c30461a2b5, 0xb199766836484420)

julia> Random.default_rng()   # ?! shouldn't this be the same state we just copied from?
TaskLocalRNG(0x6c4866be67e41b35,0x190098b53e17879a,0xe342dc7b9c59fdeb,0xb156895802bc4cb0)

julia> using Base.Threads

julia> Threads.nthreads()
1

julia> versioninfo()
Julia Version 1.8.0-DEV.798
Commit 3ae25059fb (2021-10-22 06:13 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```

I have no idea why the copy differs from the original - as far as I can tell, even the current task is the same, so no new RNG was split off! Am I doing something wrong with printing here? It's basically the same as for regular Xoshiro, and printing itself doesn't seem to change RNG either:

```
julia> Random.default_rng()
TaskLocalRNG(0x6c4866be67e41b35,0x190098b53e17879a,0xe342dc7b9c59fdeb,0xb156895802bc4cb0)

julia> Random.default_rng()
TaskLocalRNG(0x6c4866be67e41b35,0x190098b53e17879a,0xe342dc7b9c59fdeb,0xb156895802bc4cb0)

julia> Random.default_rng()
TaskLocalRNG(0x6c4866be67e41b35,0x190098b53e17879a,0xe342dc7b9c59fdeb,0xb156895802bc4cb0)
```

**Comment by Seelengrab** [comment]
Ok, when I just `dump(t)` instead of printing the state manually, I get a very different picture. Seems like there's a task for printing/background stuff that's different from the REPL, which has a different RNG state. The REPL with our task/rng state is waiting diligently though - maybe something similar is going on here? Is there a somewhat easy way/tool to inspect task state of a running julia session?

**Comment by vtjnash** [comment]
These numbers don't appear to be random, but is advanced exactly 8 numbers from where it was supposed to be generating:
0.6209946085911393 == 0.7846500004305739
```
julia> rng = Xoshiro(0x947b9af2ba269897, 0x95ae8d9a31382b32, 0x8a532dc2baa61f2e, 0x7213512241a4dfbd)
Xoshiro(0x947b9af2ba269897, 0x95ae8d9a31382b32, 0x8a532dc2baa61f2e, 0x7213512241a4dfbd)

julia> rand(rng)
0.6209946085911393

julia> rand(rng)
0.08217519705091403

julia> rand(rng)
0.7653532529104843

julia> rand(rng)
0.5444902979941714

julia> rand(rng)
0.696656487590396

julia> rand(rng)
0.40339486705752836

julia> rand(rng)
0.3460152995484739

julia> rand(rng)
0.3412018309199384

julia> rand(rng)
0.7846500004305739
```

**Comment by vtjnash** [comment]
which means the 2 states were probably:
```
orig = Xoshiro(0x7395c1c4acfb627a, 0x4c26b3294081a4a8, 0x4b551ddeca4f6ea5, 0x4da71ae5e526297b)
rng  = Xoshiro(0x947b9af2ba269897, 0x95ae8d9a31382b32, 0x8a532dc2baa61f2e, 0x7213512241a4dfbd)
```

**Comment by Seelengrab** [comment]
Very interesting! That's also consistent with the other observation [posted above](https://github.com/JuliaLang/julia/issues/42752#issuecomment-950180944)

<details>
<summary> states </summary>

```julia
julia> orig = Xoshiro(0x98eb785bda6da52d, 0xa71f2324bc045d76, 0x9739d712cfb7c053, 0xa001e265c6af9015)
Xoshiro(0x98eb785bda6da52d, 0xa71f2324bc045d76, 0x9739d712cfb7c053, 0xa001e265c6af9015)

julia> rand(orig)
0.9755253173603154

julia> rand(orig)
0.6218595743287779

julia> rand(orig)
0.18401662900007387

julia> rand(orig)
0.4942449913515099

julia> rand(orig)
0.19740142179010944

julia> rand(orig)
0.5657614748780961

julia> rand(orig)
0.5698126213082862

julia> rand(orig)
0.6621331406776867

julia> orig
Xoshiro(0x23cdaf44f4fd1c54, 0x84dec7f31d026a9c, 0x6fdbeb04a2abd21a, 0x4cd9c15a6e89152c)

julia> rand(orig)
0.45116343295850014
```
</details>

so I'd be inclined to say that finding what advances RNGs by exactly 8 numbers makes it likely to find the cause.

**Comment by Seelengrab** [comment]
The `testfun` for testing guarded seeds from above calls `rand()` with the `default_rng()` 4 times - is it possible that, for some reason, the task handling that testset is running _twice_?

**Comment by DilumAluthge** [comment]
I just saw what appears to be the same bug, on `tester_linux64`. Full log: https://build.julialang.org/#/builders/69/builds/6230

Since this is on `linux64`, we have an `rr` trace.

**Comment by Seelengrab** [comment]
Yep, exhibits the same behavior of being 8 `rand` calls behind!

**Comment by vtjnash** [comment]
Still broken, but somewhat less so?? (or more so??) https://build.julialang.org/#/builders/2/builds/76

We are still generating the wrong random number, and it is still off by 8, but now the contents of the copy and the Task are exactly the same.

**Comment by DilumAluthge** [comment]
I got an rr trace: https://buildkite.com/julialang/julia-master/builds/11189#1be3920d-621e-439a-8d43-7be5ba357a1b

Please note that the rr trace will be deleted from Buildkite in six months.

```
The global RNG seed was 0x5c2b5120001bf6fd2dfbf836dc500c5f.

 

Error in testset Test:

Test Failed at /cache/build/default-amdci5-1/julialang/julia-master/julia-1600cb97d2/share/julia/stdlib/v1.9/Test/test/runtests.jl:795

  Expression: orig == Random.default_rng()

   Evaluated: Xoshiro(0xf87f64b7bf553e41, 0x6bb192733ba008f5, 0x88582df1eaa56f74, 0xc4d459a683f010e3) == TaskLocalRNG()

Error in testset Test:

Test Failed at /cache/build/default-amdci5-1/julialang/julia-master/julia-1600cb97d2/share/julia/stdlib/v1.9/Test/test/runtests.jl:796

  Expression: rand(orig) == rand()

   Evaluated: 0.1548008544647953 == 0.9281513333593826

ERROR: LoadError: Test run finished with errors
```

**Comment by vtjnash** [comment]
Here is the cause of the fault:
```c
(rr) bt
#0  0x00007f64c6633201 in jl_genrandom (rngState=0x7f64661a1468) at /cache/build/default-amdci4-4/julialang/julia-master/src/task.c:726
#1  rng_split (to=0x7f64632c9880, from=0x7f64661a1430) at /cache/build/default-amdci4-4/julialang/julia-master/src/task.c:753
#2  ijl_new_task (start=0x7f646283de60, completion_future=<optimized out>, ssize=<optimized out>) at /cache/build/default-amdci4-4/julialang/julia-master/src/task.c:794
#3  0x00007f64af996040 in _Task () at boot.jl:444                        
#4  Task () at task.jl:5                                                                                                                                   
#5  Task () at task.jl:5                                            
#6  errormonitor () at task.jl:539
#7  julia_process_worker_67608 () at /cache/build/default-amdci4-4/julialang/julia-master/usr/share/julia/stdlib/v1.9/Distributed/src/remotecall.jl:328
#8  0x00007f64af99c00e in send_del_client_no_lock () at /cache/build/default-amdci4-4/julialang/julia-master/usr/share/julia/stdlib/v1.9/Distributed/src/remotecall.jl:306
#9  julia_finalize_ref_67633 () at /cache/build/default-amdci4-4/julialang/julia-master/usr/share/julia/stdlib/v1.9/Distributed/src/remotecall.jl:103
#10 0x00007f64af99c06c in jfptr_finalize_ref_67634.clone_1 () at abstractarray.jl:668
#11 0x00007f64c660b977 in _jl_invoke (world=<optimized out>, mfunc=<optimized out>, nargs=1, args=0x7f64a31503f8, F=0x7f64b2d320d0 <jl_system_image_data+36638224>)
    at /cache/build/default-amdci4-4/julialang/julia-master/src/gf.c:2373
#12 ijl_apply_generic (F=<optimized out>, args=args@entry=0x7f64a31503f8, nargs=nargs@entry=1) at /cache/build/default-amdci4-4/julialang/julia-master/src/gf.c:2574
#13 0x00007f64c6669d3d in jl_apply (nargs=2, args=0x7f64a31503f0) at /cache/build/default-amdci4-4/julialang/julia-master/src/julia.h:1838
#14 run_finalizer (o=<optimized out>, ff=<optimized out>, ct=<optimized out>) at /cache/build/default-amdci4-4/julialang/julia-master/src/gc.c:280
#15 0x00007f64c666acd5 in jl_gc_run_finalizers_in_list (ct=ct@entry=0x7f64661a1430, list=list@entry=0x7f64a3150570) at /cache/build/default-amdci4-4/julialang/julia-master/src/gc.c:370
#16 0x00007f64c666af69 in run_finalizers (ct=0x7f64661a1430) at /cache/build/default-amdci4-4/julialang/julia-master/src/gc.c:400
#17 run_finalizers (ct=0x7f64661a1430) at /cache/build/default-amdci4-4/julialang/julia-master/src/gc.c:378
#18 0x00007f64c666c1e9 in jl_gc_run_pending_finalizers (ct=<optimized out>, ct@entry=0x7f64661a1430) at /cache/build/default-amdci4-4/julialang/julia-master/src/gc.c:411
#19 0x00007f64c5cce88c in jl_mutex_unlock (lock=<optimized out>) at /cache/build/default-amdci4-4/julialang/julia-master/src/julia_locks.h:131
#20 jl_generate_fptr_impl (mi=<optimized out>, world=33829) at /cache/build/default-amdci4-4/julialang/julia-master/src/jitlayers.cpp:361
#21 0x00007f64c660aad8 in jl_compile_method_internal (world=33829, mi=0x7f649bd55410) at /cache/build/default-amdci4-4/julialang/julia-master/src/gf.c:2106
#22 jl_compile_method_internal (mi=0x7f649bd55410, world=33829) at /cache/build/default-amdci4-4/julialang/julia-master/src/gf.c:2047
#23 0x00007f64c660bb38 in _jl_invoke (world=33829, mfunc=<optimized out>, nargs=2, args=0x7f64a31508a8, F=0x7f64b5232a70 <jl_system_image_data+75438000>)
    at /cache/build/default-amdci4-4/julialang/julia-master/src/gf.c:2384
#24 ijl_apply_generic (F=<optimized out>, args=args@entry=0x7f64a31508a8, nargs=nargs@entry=2) at /cache/build/default-amdci4-4/julialang/julia-master/src/gf.c:2574
#25 0x00007f64c662c7bd in jl_apply (nargs=3, args=0x7f64a31508a0) at /cache/build/default-amdci4-4/julialang/julia-master/src/julia.h:1838
#26 do_call (args=args@entry=0x7f649bd39078, nargs=nargs@entry=3, s=s@entry=0x7f64a3151090) at /cache/build/default-amdci4-4/julialang/julia-master/src/interpreter.c:126
#27 0x00007f64c662bf77 in eval_value (e=e@entry=0x7f64a26eca70, s=s@entry=0x7f64a3151090) at /cache/build/default-amdci4-4/julialang/julia-master/src/interpreter.c:215
#28 0x00007f64c662d0ac in eval_stmt_value (s=0x7f64a3151090, stmt=0x7f64a26eca70) at /cache/build/default-amdci4-4/julialang/julia-master/src/interpreter.c:594
#29 eval_body (stmts=stmts@entry=0x3ebbdc00, s=s@entry=0x7f64a3151090, ip=<optimized out>, ip@entry=79, toplevel=toplevel@entry=1)
    at /cache/build/default-amdci4-4/julialang/julia-master/src/interpreter.c:594
#30 0x00007f64c662d750 in eval_body (stmts=stmts@entry=0x3ebbdc00, s=s@entry=0x7f64a3151090, ip=<optimized out>, ip@entry=40, toplevel=toplevel@entry=1)
    at /cache/build/default-amdci4-4/julialang/julia-master/src/interpreter.c:522
#31 0x00007f64c662d750 in eval_body (stmts=stmts@entry=0x3ebbdc00, s=s@entry=0x7f64a3151090, ip=<optimized out>, ip@entry=38, toplevel=toplevel@entry=1)
    at /cache/build/default-amdci4-4/julialang/julia-master/src/interpreter.c:522
#32 0x00007f64c662d750 in eval_body (stmts=<optimized out>, s=s@entry=0x7f64a3151090, ip=<optimized out>, ip@entry=0, toplevel=toplevel@entry=1)
    at /cache/build/default-amdci4-4/julialang/julia-master/src/interpreter.c:522
#33 0x00007f64c662e386 in jl_interpret_toplevel_thunk (m=m@entry=0x7f6463dff0d0, src=0x7f6468b50d90) at /cache/build/default-amdci4-4/julialang/julia-master/src/interpreter.c:750
#34 0x00007f64c66507df in jl_toplevel_eval_flex (m=m@entry=0x7f6463dff0d0, e=<optimized out>, fast=fast@entry=1, expanded=expanded@entry=0)
    at /cache/build/default-amdci4-4/julialang/julia-master/src/toplevel.c:912
#35 0x00007f64c665163b in jl_toplevel_eval_flex (m=m@entry=0x7f6463dff0d0, e=e@entry=0x7f646886cd50, fast=fast@entry=1, expanded=expanded@entry=0)
    at /cache/build/default-amdci4-4/julialang/julia-master/src/julia.h:996
#36 0x00007f64c6652b0c in ijl_toplevel_eval (m=m@entry=0x7f6463dff0d0, v=v@entry=0x7f646886cd50) at /cache/build/default-amdci4-4/julialang/julia-master/src/toplevel.c:921
#37 0x00007f64c6652c2b in ijl_toplevel_eval_in (m=0x7f6463dff0d0, ex=0x7f646886cd50) at /cache/build/default-amdci4-4/julialang/julia-master/src/toplevel.c:971
#38 0x00007f64b03eaa42 in eval () at boot.jl:370
#39 japi1_include_string_30440 () at loading.jl:1297
```
