### ISSUE TITLE
Regression: keyboard interrupt causes julia 1.7 to hang indefinitely

### ISSUE THREAD

**Issue by mwallerb** [JuliaLang/julia#43299]
After upgrading to Julia 1.7.0, interrupting scripts using Ctrl+C does not work anymore.  Instead, julia seems to interrupt running calculations (the CPU usage drops to zero) and then hangs indefinitely.

This used to work up to Julia 1.6, with or without multi-threading.

Attaching gdb to the julia process and running a backtrace reveals:

Thread 1:
```
#0  0x00007fb6601998ca in __futex_abstimed_wait_common64 () from /usr/lib/libpthread.so.0
#1  0x00007fb660193270 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#2  0x00007fb65f4720bd in usr2_handler (sig=12, info=<optimized out>, ctx=0x7fb6551aaac0)
    at /buildworker/worker/package_linux64/build/src/signals-unix.c:476
#3  <signal handler called>
(...)
```

Thread 2:
```
#0  0x00007fb660196600 in __lll_lock_wait () from /usr/lib/libpthread.so.0
#1  0x00007fb66018f503 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#2  0x00007fb65f470ef2 in jl_thread_suspend_and_get_state (tid=tid@entry=0, ctx=ctx@entry=0x7fb65a280c48)
    at /buildworker/worker/package_linux64/build/src/signals-unix.c:371
#3  0x00007fb65f47163b in jl_exit_thread0 (bt_data=0x7fb65fab3340 <bt_data>, bt_size=26, state=130)
    at /buildworker/worker/package_linux64/build/src/signals-unix.c:440
#4  signal_listener (arg=<optimized out>) at /buildworker/worker/package_linux64/build/src/signals-unix.c:843
(...)
```

Threads 3 to 12:
```
#0  0x00007fb6601998ca in __futex_abstimed_wait_common64 () from /usr/lib/libpthread.so.0
#1  0x00007fb660193270 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#2  0x00007fb647f165db in blas_thread_server () from /opt/julia-1.7.0/bin/../lib/julia/libopenblas64_.so
#3  0x00007fb66018d259 in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007fb6600b65e3 in clone () from /usr/lib/libc.so.6
```

From a quick glance there seems to be some sort of deadlock going on.

Note however that I have **not** started the script with multiple threads (I have neither set `JULIA_NUM_THREADS` nor passed a `-t` argument).

Julia version: 1.7.0 (from official sources) on x86_64
Arch Linux with glibc 2.33-5

**Comment by fredrikekre** [comment]
#43103 probably?

**Comment by mwallerb** [comment]
@fredrikekre I apologize, I have missed this issue in my duplicate search ...
closing as duplicate.
