### ISSUE TITLE
Can't build Julia `release-1.6` on MacBook M1

### ISSUE THREAD

**Issue by navidcy** [JuliaLang/julia#44688]
Having trouble building julia from the `release-1.6` branch on a MacBook M1 Mac.

```
(base) navid:julia-1.6/ (release-1.6) $ make
/bin/sh: gfortran: command not found
Traceback (most recent call last):
  File "/Users/navid/julia-1.6/contrib/normalize_triplet.py", line 121, in <module>
    }[list(filter(lambda x: re.match("\d+\.\d+(\.\d+)?", x), sys.argv[2].split()))[-1].split('.')[0]]
IndexError: list index out of range
/bin/sh: gfortran: command not found
Traceback (most recent call last):
  File "/Users/navid/julia-1.6/contrib/normalize_triplet.py", line 121, in <module>
    }[list(filter(lambda x: re.match("\d+\.\d+(\.\d+)?", x), sys.argv[2].split()))[-1].split('.')[0]]
IndexError: list index out of range
/bin/sh: gfortran: command not found
/bin/sh: gfortran: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   530  100   530    0     0    558      0 --:--:-- --:--:-- --:--:--   560
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
make[1]: *** [/Users/navid/julia-1.6/deps/srccache/CompilerSupportLibraries.v0.5.0+0..tar.gz] Error 22
make: *** [julia-deps] Error 2
```

**Comment by giordano** [comment]
The M1 isn't supported for v1.6

**Comment by navidcy** [comment]
I saw this
https://github.com/JuliaLang/julia/blob/9a16c081b4b2bc81bd135f7ceb993f32bffe58b3/base/cpuid.jl#L62
at
https://github.com/JuliaLang/julia/compare/v1.6.5...9a16c081b4b2bc81bd135f7
and thought support for M1 came to 1.6.6.

**Comment by giordano** [comment]
That has _nothing_ to do with it.
