### ISSUE TITLE
Possible invalid free in suitesparse tests.

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#4977]
Got the following when running the suitesparse tests. Unfortunately due to lack of JIT symbolization and since asan messes with gdb, I can't say what that function is. Might be worth running through valgrind with `vgdb` to get symbolization. Mostly leaving this here so I don't forget. 
```
     * suitesparse
=================================================================
==80052==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x0000013185c0 in thread T0
    #0 0x477979 in free /home/kfischer/julia/deps/llvm-svn/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64
    #1 0x7fffce5b4e6d (+0x1e6d)
    #2 0x7fffce5b4235 (+0x1235)
    #3 0x7fffce5b4025 (+0x1025)
    #4 0x7ffff0398ba2 in jl_apply_generic (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xdc2ba2)
    #5 0x7ffff0469c80 in do_call (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xe93c80)
    #6 0x7ffff0465d20 in eval (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xe8fd20)
    #7 0x7ffff04664ac in eval (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xe904ac)
    #8 0x7ffff046953a in eval_body (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xe9353a)
    #9 0x7ffff04699eb in jl_interpret_toplevel_thunk_with (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xe939eb)
    #10 0x7ffff048b260 in jl_toplevel_eval_flex (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xeb5260)
    #11 0x7ffff048c3d3 in jl_parse_eval_all (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xeb63d3)
    #12 0x7ffff048cb36 in jl_load (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xeb6b36)
    #13 0x7fffd666611a (+0x111a)
    #14 0x7ffff0398ba2 in jl_apply_generic (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xdc2ba2)
    #15 0x7ffff03a8e7c in jl_f_apply (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xdd2e7c)
    #16 0x7fffdcbe50ba (+0xba)
    #17 0x7fffd67f02d5 (+0x2d5)
    #18 0x7fffd66b90b5 (+0xb5)
    #19 0x7ffff0398ba2 in jl_apply_generic (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xdc2ba2)
    #20 0x7ffff03a8e53 in jl_f_apply (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xdd2e53)
    #21 0x7fffdcc100fb (+0x40fb)
    #22 0x7ffff0398ba2 in jl_apply_generic (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xdc2ba2)
    #23 0x7ffff03a8e53 in jl_f_apply (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xdd2e53)
    #24 0x7fffd67be4ba (+0x4ba)
    #25 0x7ffff04769a2 in switch_stack (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xea09a2)
    #26 0x7ffff04768eb in switch_stack (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xea08eb)
    #27 0x7ffff04761a7 in julia_trampoline (/home/kfischer/julia/usr/bin/../lib/libjulia.so+0xea01a7)
    #28 0x7fffee1e176c in __libc_start_main /build/buildd/eglibc-2.15/csu/libc-start.c:226
    #29 0x48e01c in _start (/home/kfischer/julia/usr/bin/julia-readline+0x48e01c)

AddressSanitizer can not describe address in more detail (wild memory access suspected).
SUMMARY: AddressSanitizer: bad-free /home/kfischer/julia/deps/llvm-svn/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:64 free
==80052==ABORTING
```

**Comment by ViralBShah** [comment]
Please reopen if we can have a test case to reproduce.
